export interface MEIndicator {
  id: string;
  principle: 'livelihoods' | 'climate' | 'biodiversity' | 'water' | 'soil' | 'animal_welfare';
  outcome: string;
  indicator: string;
  metric: string;
  measurementMethod: string;
  frameworkAlignment: string;
  applicableCommodity: string;
  frequency: string;
  tier: 'core' | 'additional';
}

export const meFramework: MEIndicator[] = [
  // ═══════════════════════════════════════
  // LIVELIHOODS — 14 indicators
  // ═══════════════════════════════════════
  {
    id: 'liv-01',
    principle: 'livelihoods',
    outcome: 'Improved inclusion, social equity and safety',
    indicator: 'Households reporting reduced human-wildlife conflict',
    metric: '% of farmers adopting conflict mitigation; incidents per year',
    measurementMethod: 'Household surveys (gender-disaggregated), focus groups, local wildlife authority records',
    frameworkAlignment: 'OP2B biodiversity indicator framework',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'liv-02',
    principle: 'livelihoods',
    outcome: 'Improved inclusion, social equity and safety',
    indicator: 'Women in decision-making and economic activities',
    metric: '% women in leadership roles; % women generating independent income',
    measurementMethod: 'Surveys (gender-disaggregated), participatory focus groups, membership records',
    frameworkAlignment: 'UN SDG 5 (Gender Equality)',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'liv-03',
    principle: 'livelihoods',
    outcome: 'Improved inclusion, social equity and safety',
    indicator: 'Young people engaged in regenerative practices',
    metric: '% participants aged 18-35 in key activities; % youth in leadership/technical roles',
    measurementMethod: 'Surveys (age-disaggregated), youth engagement metrics, community group membership',
    frameworkAlignment: 'UN SDG 8 (Decent Work), FAO youth engagement guidelines',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'liv-04',
    principle: 'livelihoods',
    outcome: 'Improved inclusion, social equity and safety',
    indicator: 'Representation of ethnic groups in decision-making',
    metric: '% leadership roles held by indigenous/ethnic minority members',
    measurementMethod: 'Surveys (ethnicity-disaggregated), participatory focus groups, demographic analysis',
    frameworkAlignment: 'UN SDG 10 (Reduced Inequalities), IPLC engagement guidelines',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'liv-05',
    principle: 'livelihoods',
    outcome: 'Increased capacity and autonomy',
    indicator: 'Farmers demonstrating autonomous implementation',
    metric: '% farmers independently managing regen systems without external support (gender-disaggregated)',
    measurementMethod: 'Household survey',
    frameworkAlignment: 'OP2B capacity-building indicators',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'liv-06',
    principle: 'livelihoods',
    outcome: 'Increased capacity and autonomy',
    indicator: 'Perception of regenerative agriculture for brighter farming future',
    metric: 'Aggregate survey score (gender-disaggregated)',
    measurementMethod: 'Household survey',
    frameworkAlignment: 'CI technical experts, OP2B',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'liv-07',
    principle: 'livelihoods',
    outcome: 'Improved market access and economic outcomes',
    indicator: 'Value produced per hectare',
    metric: '% increase in total economic value per hectare over time',
    measurementMethod: 'Farm production records, yield data, market prices',
    frameworkAlignment: 'OP2B',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'liv-08',
    principle: 'livelihoods',
    outcome: 'Improved market access and economic outcomes',
    indicator: 'Outputs meeting defined quality standards',
    metric: '% outputs achieving certification-specific quality thresholds',
    measurementMethod: 'Third-party certifications, sampling/testing (fiber micron count, hide quality), buyer reports',
    frameworkAlignment: 'Fair Trade, Rainforest Alliance, OP2B',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'liv-09',
    principle: 'livelihoods',
    outcome: 'Improved market access and economic outcomes',
    indicator: 'Farmers with improved access to market',
    metric: '% farmers (gender-disaggregated) with measurable improvement in market access',
    measurementMethod: 'Household survey. Define access in context (auctions, direct sales, contracts)',
    frameworkAlignment: 'SBTN Landscape Engagement Target metric 3.4',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'liv-10',
    principle: 'livelihoods',
    outcome: 'Improved market access and economic outcomes',
    indicator: 'Farmers accessing diverse income streams',
    metric: '% farmers in carbon credits, PES, intercropping; total revenue generated',
    measurementMethod: 'Household survey, financial records, carbon credit/PES registration data',
    frameworkAlignment: 'REDD+, OP2B income diversification',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'liv-11',
    principle: 'livelihoods',
    outcome: 'Improved market access and economic outcomes',
    indicator: 'Farmers receiving a better price per volume',
    metric: 'Absolute price per volume; % price increase for participants',
    measurementMethod: 'Household survey, comparison with local farmgate/FOB price at baseline and post',
    frameworkAlignment: 'SBTN metric 3.1, 3.4',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'liv-12',
    principle: 'livelihoods',
    outcome: 'Improved market access and economic outcomes',
    indicator: 'Net income change',
    metric: 'Local currency & USD per year; % increase in net income',
    measurementMethod: 'Household survey, financial records, comparison with local benchmarks',
    frameworkAlignment: 'OP2B, SBTN metric 3.4',
    applicableCommodity: 'All',
    frequency: 'Biannually',
    tier: 'core',
  },
  {
    id: 'liv-13',
    principle: 'livelihoods',
    outcome: 'Improved market access and economic outcomes',
    indicator: 'Gap between actual income and Living Income Benchmark',
    metric: 'Local currency & USD per year',
    measurementMethod: 'Household survey, comparison with Living Income Community of Practice benchmarks',
    frameworkAlignment: 'SBTN metric 3.1, 3.4',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'liv-14',
    principle: 'livelihoods',
    outcome: 'Improved market access and economic outcomes',
    indicator: 'People trained in financial capabilities',
    metric: 'Number of farmers trained',
    measurementMethod: 'Training attendance records',
    frameworkAlignment: 'SBTN metric 3.4',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },

  // ═══════════════════════════════════════
  // CLIMATE — 5 indicators
  // ═══════════════════════════════════════
  {
    id: 'cli-01',
    principle: 'climate',
    outcome: 'Increase resilience',
    indicator: 'Farmer adaptive capacity',
    metric: 'Survey responses pre and post project implementation',
    measurementMethod: 'Household survey',
    frameworkAlignment: 'N/A',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'cli-02',
    principle: 'climate',
    outcome: 'Minimize GHG emissions',
    indicator: 'Greenhouse gas emissions',
    metric: 'MT CO2e per yield or metric ton of product; MT CO2e total',
    measurementMethod: 'Standardized IPCC emission factors, verified with remote sensing and satellite imagery',
    frameworkAlignment: 'OP2B, SBTi',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'cli-03',
    principle: 'climate',
    outcome: 'Increase carbon sequestration',
    indicator: 'Above-ground carbon sequestration',
    metric: 'MT CO2e total',
    measurementMethod: 'Satellite imagery verified with ground truth data',
    frameworkAlignment: 'OP2B, SBTi',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'cli-04',
    principle: 'climate',
    outcome: 'Increase carbon sequestration',
    indicator: 'Soil carbon sequestration',
    metric: 'MT CO2e total',
    measurementMethod: 'Soil lab data for SOC at specified depths + bulk density measurements',
    frameworkAlignment: 'OP2B, SBTi',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'cli-05',
    principle: 'climate',
    outcome: 'Total project carbon balance',
    indicator: 'Net carbon balance',
    metric: 'MT CO2e total (net: sequestration minus emissions)',
    measurementMethod: 'Sum of total carbon sequestration minus total GHG emissions',
    frameworkAlignment: 'OP2B, SBTi, SBTN Indicator 1.13',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },

  // ═══════════════════════════════════════
  // BIODIVERSITY — 9 indicators
  // ═══════════════════════════════════════
  {
    id: 'bio-01',
    principle: 'biodiversity',
    outcome: 'Enhanced biodiversity and ecosystem health',
    indicator: 'Soil microbial diversity',
    metric: 'Shannon/Simpson diversity indices; microbial biomass',
    measurementMethod: 'Handful soil observation (qualitative) + soil eDNA extraction (comprehensive)',
    frameworkAlignment: 'N/A',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'bio-02',
    principle: 'biodiversity',
    outcome: 'Enhanced biodiversity and ecosystem health',
    indicator: 'On-farm area planted with native trees/perennials',
    metric: '% natural habitat out of total project area',
    measurementMethod: 'Field surveys, satellite imagery, farm records',
    frameworkAlignment: 'OP2B, SBTN',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'bio-03',
    principle: 'biodiversity',
    outcome: 'Enhanced biodiversity and ecosystem health',
    indicator: 'Natural/restored habitat in agricultural landscapes',
    metric: '% natural habitat out of total project area',
    measurementMethod: 'Satellite imagery and GIS mapping, field surveys',
    frameworkAlignment: 'OP2B, SBTN metric 1.4 (area under restoration)',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'bio-04',
    principle: 'biodiversity',
    outcome: 'Enhanced biodiversity and ecosystem health',
    indicator: 'Crop diversity',
    metric: 'Crop diversity per km² (modified Hill-Shannon Index)',
    measurementMethod: 'Crop vegetation plots or transects',
    frameworkAlignment: 'OP2B',
    applicableCommodity: 'All',
    frequency: 'Annually or biannually',
    tier: 'core',
  },
  {
    id: 'bio-05',
    principle: 'biodiversity',
    outcome: 'Enhanced biodiversity and ecosystem health',
    indicator: 'Indicator species (native pollinators and/or pest predators)',
    metric: '% of farms where priority species stable/increasing in abundance',
    measurementMethod: 'Yellow pan traps, pitfall traps, sweep netting, visual surveys',
    frameworkAlignment: 'OP2B, SBTN',
    applicableCommodity: 'All',
    frequency: 'Seasonally',
    tier: 'core',
  },
  {
    id: 'bio-06',
    principle: 'biodiversity',
    outcome: 'Enhanced biodiversity and ecosystem health',
    indicator: 'Landscape connectivity',
    metric: 'Connectance index; proportion of NSH core area; field border density',
    measurementMethod: 'GIS mapping and analysis, field surveys, participatory mapping',
    frameworkAlignment: 'OP2B',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'additional',
  },
  {
    id: 'bio-07',
    principle: 'biodiversity',
    outcome: 'Enhanced biodiversity and ecosystem health',
    indicator: 'Hectares under improved wildlife management',
    metric: 'Total hectares with documented management plans and restoration efforts',
    measurementMethod: 'GIS mapping, conservation program records, visual verification',
    frameworkAlignment: 'SBTN Landscape Engagement Target',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'additional',
  },
  {
    id: 'bio-08',
    principle: 'biodiversity',
    outcome: 'Increase conservation/restoration area',
    indicator: 'Land where conversion to non-forest/agricultural use prevented',
    metric: 'Total hectares under protection or with conversion avoidance commitments',
    measurementMethod: 'GIS mapping, remote sensing, land-use change analysis, community plans',
    frameworkAlignment: 'REDD+, Aichi Target 5',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'additional',
  },
  {
    id: 'bio-09',
    principle: 'biodiversity',
    outcome: 'Increase conservation/restoration area',
    indicator: 'On-farm area set aside for conservation or restoration',
    metric: 'Hectares or % of farm area',
    measurementMethod: 'Satellite imagery, GIS mapping, farmer surveys, field verification',
    frameworkAlignment: 'N/A',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'additional',
  },

  // ═══════════════════════════════════════
  // WATER — 7 indicators
  // ═══════════════════════════════════════
  {
    id: 'wat-01',
    principle: 'water',
    outcome: 'Increase water efficiency',
    indicator: 'Water supply reliability',
    metric: 'ML water recharged; reduced ML water withdrawn',
    measurementMethod: 'Capture/infiltration method for rainwater; flow meters for irrigation',
    frameworkAlignment: 'VWBA, SBTN',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'wat-02',
    principle: 'water',
    outcome: 'Increase water efficiency',
    indicator: 'Water withdrawal and consumption for irrigation',
    metric: 'ML per hectare of cultivated land',
    measurementMethod: 'Farm-level water monitoring, FAO Irrigation Paper 56, CROPWAT model, remote sensing for ET',
    frameworkAlignment: 'SBTN watershed target',
    applicableCommodity: 'All',
    frequency: 'Seasonally',
    tier: 'core',
  },
  {
    id: 'wat-03',
    principle: 'water',
    outcome: 'Reduce water pollution / improve quality',
    indicator: 'Fertilizer and pesticide application rates',
    metric: 'Kg nitrogen and phosphorus per hectare',
    measurementMethod: 'Household survey / farm records',
    frameworkAlignment: 'OP2B, SBTN',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'wat-04',
    principle: 'water',
    outcome: 'Reduce water pollution / improve quality',
    indicator: 'Nutrient loading of N and P to surface water',
    metric: 'Kg per year; % reduction from current rate',
    measurementMethod: 'Nutrient load modeling along flow paths; nutrient balance analysis',
    frameworkAlignment: 'OP2B, SBTN',
    applicableCommodity: 'All',
    frequency: 'Annually or seasonally',
    tier: 'core',
  },
  {
    id: 'wat-05',
    principle: 'water',
    outcome: 'Improved water use efficiency',
    indicator: 'Aquatic habitat restoration / recharge rate',
    metric: 'Recharge rate maintained or increased',
    measurementMethod: 'Groundwater monitoring wells, infiltration tests, remote sensing, hydrological models',
    frameworkAlignment: 'VWBA',
    applicableCommodity: 'All',
    frequency: 'Annually or biannually',
    tier: 'additional',
  },
  {
    id: 'wat-06',
    principle: 'water',
    outcome: 'Improved water use efficiency',
    indicator: 'Source of irrigation water',
    metric: 'Types and volumes of irrigation water sources',
    measurementMethod: 'Household survey and field verification',
    frameworkAlignment: 'N/A',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'additional',
  },
  {
    id: 'wat-07',
    principle: 'water',
    outcome: 'Reduce water pollution',
    indicator: 'Use of pesticides, herbicides and synthetic applications',
    metric: 'Kg per hectare of productive land',
    measurementMethod: 'Household survey',
    frameworkAlignment: 'SBTN',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'additional',
  },

  // ═══════════════════════════════════════
  // SOIL — 9 indicators
  // ═══════════════════════════════════════
  {
    id: 'sol-01',
    principle: 'soil',
    outcome: 'Increased soil health',
    indicator: 'Ground cover (proxy for soil erosion)',
    metric: '% of soil surface covered',
    measurementMethod: 'Remote sensing (drones/satellite), quadrat sampling, visual assessment (minimum 70% recommended)',
    frameworkAlignment: 'OP2B',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'sol-02',
    principle: 'soil',
    outcome: 'Increased soil health',
    indicator: 'Soil organic carbon',
    metric: 'g C per kg soil (oven-dry basis)',
    measurementMethod: 'Dry combustion (elemental analyzer), loss-on-ignition (LOI), mid-infrared spectroscopy (MIRS)',
    frameworkAlignment: 'OP2B, SBTi',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'sol-03',
    principle: 'soil',
    outcome: 'Increased soil health',
    indicator: 'Soil invertebrate diversity',
    metric: 'Number of species and organisms per species (score 1-5)',
    measurementMethod: 'Quadrat sampling, soil extraction, hand sorting or Berlese funnel, biodiversity index',
    frameworkAlignment: 'OP2B',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'sol-04',
    principle: 'soil',
    outcome: 'Increased soil health',
    indicator: 'Soil microbial diversity',
    metric: 'Microbial biomass and diversity indices',
    measurementMethod: 'Handful soil observation (qualitative) + soil eDNA extraction',
    frameworkAlignment: 'OP2B',
    applicableCommodity: 'All',
    frequency: 'Quarterly or semi-annually',
    tier: 'core',
  },
  {
    id: 'sol-05',
    principle: 'soil',
    outcome: 'Increased soil health',
    indicator: 'Infiltration rate',
    metric: 'mm/hr',
    measurementMethod: 'Infiltration ring test',
    frameworkAlignment: 'OP2B',
    applicableCommodity: 'All',
    frequency: 'Seasonally',
    tier: 'core',
  },
  {
    id: 'sol-06',
    principle: 'soil',
    outcome: 'Increased soil health',
    indicator: 'Soil nutrient availability',
    metric: 'mg/kg plant-available macro/micronutrients (N, P, K, SOM)',
    measurementMethod: 'Lab analysis; on-farm soil nutrient test kits for approximation',
    frameworkAlignment: 'OP2B',
    applicableCommodity: 'All',
    frequency: 'Annually or seasonally',
    tier: 'additional',
  },
  {
    id: 'sol-07',
    principle: 'soil',
    outcome: 'Increased soil health',
    indicator: 'Soil water holding capacity (green water)',
    metric: 'Soil water holding capacity',
    measurementMethod: 'Lab: gravimetric or pressure plate method. Field: field capacity test',
    frameworkAlignment: 'OP2B',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'additional',
  },
  {
    id: 'sol-08',
    principle: 'soil',
    outcome: 'Increased soil health',
    indicator: 'Soil bulk density at 3 depths (0-10, 10-30, 30-60 cm)',
    metric: 'Mass/volume (g/cm³). >1.6 g/cm³ restricts root growth.',
    measurementMethod: 'Lab: soil core sampler. Field: excavation with metal cylinder',
    frameworkAlignment: 'OP2B',
    applicableCommodity: 'All',
    frequency: 'Annually or biannually',
    tier: 'additional',
  },
  {
    id: 'sol-09',
    principle: 'soil',
    outcome: 'Increased soil health',
    indicator: 'Crop rotation / grazing rotation diversity',
    metric: 'Number of rotations per year; number of crops per ha per cycle',
    measurementMethod: 'Household survey',
    frameworkAlignment: 'N/A',
    applicableCommodity: 'All',
    frequency: 'Annually',
    tier: 'additional',
  },

  // ═══════════════════════════════════════
  // ANIMAL WELFARE — 13 indicators
  // ═══════════════════════════════════════
  {
    id: 'aw-01',
    principle: 'animal_welfare',
    outcome: 'Good feeding',
    indicator: 'Water availability',
    metric: '% animals with access to functioning, clean, accessible water points',
    measurementMethod: 'Field inspections, household survey, photographic evidence',
    frameworkAlignment: 'AWIN (sheep/goats), Welfare Quality (cattle)',
    applicableCommodity: 'Leather (cattle), Wool (sheep), Cashmere (goats)',
    frequency: 'Biannually',
    tier: 'core',
  },
  {
    id: 'aw-02',
    principle: 'animal_welfare',
    outcome: 'Good feeding',
    indicator: 'Body condition score',
    metric: '% animals within optimal range (3-4 on 1-5 scale)',
    measurementMethod: 'Visual assessment and regular monitoring per AWIN/Welfare Quality protocols',
    frameworkAlignment: 'AWIN, Welfare Quality',
    applicableCommodity: 'Leather (cattle), Wool (sheep), Cashmere (goats)',
    frequency: 'Biannually',
    tier: 'core',
  },
  {
    id: 'aw-03',
    principle: 'animal_welfare',
    outcome: 'Good housing',
    indicator: 'Comfort around resting (shade/shelter access)',
    metric: '% animals with access to shade or shelter',
    measurementMethod: 'Visual inspection and farm layout analysis',
    frameworkAlignment: 'AWIN, Welfare Quality',
    applicableCommodity: 'Leather (cattle), Wool (sheep), Cashmere (goats)',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'aw-04',
    principle: 'animal_welfare',
    outcome: 'Good housing',
    indicator: 'Ease of movement / stocking density',
    metric: 'Stocking density ratios (animals per m²)',
    measurementMethod: 'Measure enclosure area and animal count. Species-specific AWIN/WQ thresholds',
    frameworkAlignment: 'AWIN, Welfare Quality',
    applicableCommodity: 'Leather (cattle), Wool (sheep), Cashmere (goats)',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'aw-05',
    principle: 'animal_welfare',
    outcome: 'Good housing',
    indicator: 'Number and kind of welfare practices implemented',
    metric: 'Number of farms implementing practices; which practices (bare minimum required)',
    measurementMethod: 'Household survey and inspections per AWIN protocols',
    frameworkAlignment: 'N/A',
    applicableCommodity: 'Leather (cattle), Wool (sheep), Cashmere (goats)',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'aw-06',
    principle: 'animal_welfare',
    outcome: 'Good health',
    indicator: 'Absence of disease',
    metric: '% animals showing no visible signs of disease',
    measurementMethod: 'Visual inspection: fleece cleanliness, nasal discharge, body condition, udder health (cattle)',
    frameworkAlignment: 'AWIN, Welfare Quality',
    applicableCommodity: 'Leather (cattle), Wool (sheep), Cashmere (goats)',
    frequency: 'Biannually',
    tier: 'core',
  },
  {
    id: 'aw-07',
    principle: 'animal_welfare',
    outcome: 'Good health',
    indicator: 'Absence of injuries',
    metric: '% animals without injuries (lameness, lesions)',
    measurementMethod: 'Visual inspection for lameness, body lesions, leg injuries, claw overgrowth',
    frameworkAlignment: 'AWIN, Welfare Quality',
    applicableCommodity: 'Leather (cattle), Wool (sheep), Cashmere (goats)',
    frequency: 'Biannually',
    tier: 'core',
  },
  {
    id: 'aw-08',
    principle: 'animal_welfare',
    outcome: 'Good health',
    indicator: 'Mortality rate',
    metric: '% reduction in annual mortality rate over time',
    measurementMethod: 'Farm records, field inspections',
    frameworkAlignment: 'AWIN',
    applicableCommodity: 'Leather (cattle), Wool (sheep), Cashmere (goats)',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'aw-09',
    principle: 'animal_welfare',
    outcome: 'Good health',
    indicator: 'Wildlife-livestock conflict',
    metric: '% farms recording and mitigating conflict incidents',
    measurementMethod: 'Household surveys, field inspections, farm records',
    frameworkAlignment: 'AWIN',
    applicableCommodity: 'Leather (cattle), Wool (sheep), Cashmere (goats)',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'aw-10',
    principle: 'animal_welfare',
    outcome: 'Appropriate behavior',
    indicator: 'Expression of social behavior',
    metric: '% animals showing positive social interactions',
    measurementMethod: 'Observation of group behaviors (no isolation or stereotyping)',
    frameworkAlignment: 'AWIN, Welfare Quality',
    applicableCommodity: 'Leather (cattle), Wool (sheep), Cashmere (goats)',
    frequency: 'Annually',
    tier: 'additional',
  },
  {
    id: 'aw-11',
    principle: 'animal_welfare',
    outcome: 'Appropriate behavior',
    indicator: 'Good human-animal relationship',
    metric: '% animals approaching familiar human within defined time',
    measurementMethod: 'Latency measurement during calm interaction. Species-specific.',
    frameworkAlignment: 'AWIN, Welfare Quality',
    applicableCommodity: 'Leather (cattle), Wool (sheep), Cashmere (goats)',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'aw-12',
    principle: 'animal_welfare',
    outcome: 'Education and improved economic productivity',
    indicator: 'Economic benefits of improved animal welfare',
    metric: '% increase in farm income; % increase in herd productivity; avg market value per animal',
    measurementMethod: 'Household surveys, farm records, market data',
    frameworkAlignment: 'AWIN',
    applicableCommodity: 'Leather (cattle), Wool (sheep), Cashmere (goats)',
    frequency: 'Annually',
    tier: 'core',
  },
  {
    id: 'aw-13',
    principle: 'animal_welfare',
    outcome: 'Education and improved economic productivity',
    indicator: 'Welfare education',
    metric: '% farmers/workers trained in animal welfare practices',
    measurementMethod: 'Household survey, training session records, % workforce trained',
    frameworkAlignment: 'AWIN',
    applicableCommodity: 'Leather (cattle), Wool (sheep), Cashmere (goats)',
    frequency: 'Annually',
    tier: 'core',
  },
];

export function getIndicatorsByPrinciple(principle: string): MEIndicator[] {
  return meFramework.filter((i) => i.principle === principle);
}

export function getCoreIndicators(principle: string): MEIndicator[] {
  return meFramework.filter((i) => i.principle === principle && i.tier === 'core');
}

// Summary counts per principle:
// Livelihoods: 14 | Climate: 5 | Biodiversity: 9 | Water: 7 | Soil: 9 | Animal Welfare: 13
// TOTAL: 57 indicators
