// Ecological claims seed data — 6 structured claims per project, one per CI principle.
// Represents multi-outcome monitoring data reframed as verifiable structured claims
// ready for Regen Registry anchoring.

export type ClaimPrinciple = 'climate' | 'soil' | 'water' | 'biodiversity' | 'livelihoods' | 'animal_welfare';
export type ClaimStatus = 'active' | 'draft' | 'pending';

export interface EcologicalClaim {
  id: string; // format: CI-[PROJECT_CODE]-[PRINCIPLE_CODE]-[YEAR]-[SEQ]
  principle: ClaimPrinciple;
  statement: string; // concise structured claim statement, max 12 words
  evidenceMethod: string;
  alignmentStandard: string;
  status: ClaimStatus;
  issuedDate: string | null;
  areaHa: number | null;
}

export interface ProjectClaims {
  projectId: string;
  claims: EcologicalClaim[];
}

// ── 2021 Grant Cycle — all claims active ─────────────────────────────────────

const mongoliaClaims: ProjectClaims = {
  projectId: 'mongolia-cashmere',
  claims: [
    {
      id: 'CI-MNG-CLI-2024-001',
      principle: 'climate',
      statement: '342,000 ha under rotational grazing — mean temp trend +0.3°C/5yr',
      evidenceMethod: 'ERA5 satellite · 5yr baseline · MODIS NDVI anomaly detection',
      alignmentStandard: 'GHG Protocol Land Sector',
      status: 'active',
      issuedDate: '2024-05-06',
      areaHa: 342000,
    },
    {
      id: 'CI-MNG-SOI-2024-001',
      principle: 'soil',
      statement: 'SOC baseline 18.4 tC/ha · 12 depth strata sampled · NIRS spectroscopy',
      evidenceMethod: 'NIRS spectroscopy · bulk density cores · 0–30 cm depth profile',
      alignmentStandard: 'Verra VM0042',
      status: 'active',
      issuedDate: '2024-05-06',
      areaHa: 185000,
    },
    {
      id: 'CI-MNG-WAT-2024-001',
      principle: 'water',
      statement: 'Soil infiltration improved 22% via rest-rotation grazing on 185,000 ha',
      evidenceMethod: 'Infiltrometer field tests · 3yr pre-post comparison · 120 sample plots',
      alignmentStandard: 'Verra W+',
      status: 'active',
      issuedDate: '2024-05-06',
      areaHa: 185000,
    },
    {
      id: 'CI-MNG-BIO-2024-001',
      principle: 'biodiversity',
      statement: '342,000 ha steppe under co-management — Pallas\'s cat sign confirmed',
      evidenceMethod: 'Camera trap grids · transect surveys · iNaturalist citizen science',
      alignmentStandard: 'TNFD / SBTN',
      status: 'active',
      issuedDate: '2024-05-06',
      areaHa: 342000,
    },
    {
      id: 'CI-MNG-LIV-2024-001',
      principle: 'livelihoods',
      statement: '1,200 herder households earning 18% premium via SFA certification',
      evidenceMethod: 'Household income surveys · SFA certification records · trader invoices',
      alignmentStandard: 'SDG 1.4 / SDG 2.3',
      status: 'active',
      issuedDate: '2024-05-06',
      areaHa: 145000,
    },
    {
      id: 'CI-MNG-AWL-2024-001',
      principle: 'animal_welfare',
      statement: 'Cashmere goat welfare standards applied across 342,000 ha — SFA certified',
      evidenceMethod: 'SFA audit protocol · veterinary inspection records · herd density monitoring',
      alignmentStandard: 'Five Freedoms Framework',
      status: 'active',
      issuedDate: '2024-05-06',
      areaHa: 342000,
    },
  ],
};

const indiaOcaClaims: ProjectClaims = {
  projectId: 'india-cotton-oca',
  claims: [
    {
      id: 'CI-IND-CLI-2024-001',
      principle: 'climate',
      statement: '53,500 ha organic cotton — synthetic fertiliser N₂O emissions eliminated',
      evidenceMethod: 'IPCC Tier 1 emission factors · input purchase records · satellite crop mapping',
      alignmentStandard: 'GHG Protocol Land Sector',
      status: 'active',
      issuedDate: '2024-04-22',
      areaHa: 53500,
    },
    {
      id: 'CI-IND-SOI-2024-001',
      principle: 'soil',
      statement: 'SOC baseline 11.2 tC/ha · 8 strata sampled · organic transition documented',
      evidenceMethod: 'Walkley-Black lab analysis · GPS-tagged composite cores · 3yr baseline',
      alignmentStandard: 'Verra VM0042',
      status: 'active',
      issuedDate: '2024-04-22',
      areaHa: 28000,
    },
    {
      id: 'CI-IND-WAT-2024-001',
      principle: 'water',
      statement: 'Drip irrigation adoption reduced water use 31% across 28,000 ha',
      evidenceMethod: 'Flow meter records · farmer self-reporting · satellite ET estimation',
      alignmentStandard: 'Verra W+',
      status: 'active',
      issuedDate: '2024-04-22',
      areaHa: 28000,
    },
    {
      id: 'CI-IND-BIO-2024-001',
      principle: 'biodiversity',
      statement: '53,500 ha free of synthetic pesticides — 14 pollinator species documented',
      evidenceMethod: 'Pollinator transect surveys · pesticide purchase records · field observation logs',
      alignmentStandard: 'TNFD / SBTN',
      status: 'active',
      issuedDate: '2024-04-22',
      areaHa: 53500,
    },
    {
      id: 'CI-IND-LIV-2024-001',
      principle: 'livelihoods',
      statement: '50,000 smallholders earning 10% organic premium — 60% women-led farms',
      evidenceMethod: 'OCA farmer records · certification audits · gender-disaggregated income surveys',
      alignmentStandard: 'SDG 1.4 / SDG 2.3',
      status: 'active',
      issuedDate: '2024-04-22',
      areaHa: 32000,
    },
    {
      id: 'CI-IND-AWL-2024-001',
      principle: 'animal_welfare',
      statement: 'Soil biota health index 7.4/10 — no neonicotinoid use across 53,500 ha',
      evidenceMethod: 'Soil invertebrate surveys · pesticide register audit · earthworm density counts',
      alignmentStandard: 'Pollinator Health Standard',
      status: 'active',
      issuedDate: '2024-04-22',
      areaHa: 53500,
    },
  ],
};

const argentinaLeatherClaims: ProjectClaims = {
  projectId: 'argentina-leather',
  claims: [
    {
      id: 'CI-ARG-L-CLI-2024-001',
      principle: 'climate',
      statement: '120,000 ha Chaco under sustainable grazing — deforestation pressure reduced',
      evidenceMethod: 'Global Forest Watch deforestation alerts · Landsat 8 change detection · 5yr baseline',
      alignmentStandard: 'GHG Protocol Land Sector',
      status: 'active',
      issuedDate: '2024-05-14',
      areaHa: 120000,
    },
    {
      id: 'CI-ARG-L-SOI-2024-001',
      principle: 'soil',
      statement: 'SOC baseline 22.1 tC/ha · 10 depth strata · Chaco clay-loam profile',
      evidenceMethod: 'Wet oxidation lab analysis · GPS composite cores · 0–50 cm depth profile',
      alignmentStandard: 'Verra VM0042',
      status: 'active',
      issuedDate: '2024-05-14',
      areaHa: 65000,
    },
    {
      id: 'CI-ARG-L-WAT-2024-001',
      principle: 'water',
      statement: 'Riparian buffer zones restored on 18 waterways — sediment load down 27%',
      evidenceMethod: 'Turbidity sensors · seasonal water quality sampling · GIS riparian mapping',
      alignmentStandard: 'Verra W+',
      status: 'active',
      issuedDate: '2024-05-14',
      areaHa: 45000,
    },
    {
      id: 'CI-ARG-L-BIO-2024-001',
      principle: 'biodiversity',
      statement: '120,000 ha dry Chaco woodland under conservation management — jaguar corridor',
      evidenceMethod: 'Camera trap network · acoustic monitoring · vegetation structure surveys',
      alignmentStandard: 'TNFD / SBTN',
      status: 'active',
      issuedDate: '2024-05-14',
      areaHa: 120000,
    },
    {
      id: 'CI-ARG-L-LIV-2024-001',
      principle: 'livelihoods',
      statement: '340 Indigenous producers accessing sustainable leather supply chain premium',
      evidenceMethod: 'Solidaridad community income surveys · offtake agreements · FPIC documentation',
      alignmentStandard: 'SDG 1.4 / SDG 2.3',
      status: 'active',
      issuedDate: '2024-05-14',
      areaHa: 65000,
    },
    {
      id: 'CI-ARG-L-AWL-2024-001',
      principle: 'animal_welfare',
      statement: 'Criollo cattle welfare protocols applied — no feedlot finishing on 120,000 ha',
      evidenceMethod: 'Veterinary farm audits · stocking density records · producer declarations',
      alignmentStandard: 'Five Freedoms Framework',
      status: 'active',
      issuedDate: '2024-05-14',
      areaHa: 120000,
    },
  ],
};

const spainGoatClaims: ProjectClaims = {
  projectId: 'spain-goat-leather',
  claims: [
    {
      id: 'CI-ESP-CLI-2024-001',
      principle: 'climate',
      statement: '17,000 ha Mediterranean scrubland under regenerative goat grazing management',
      evidenceMethod: 'ERA5 satellite · MODIS albedo tracking · 4yr biomass baseline',
      alignmentStandard: 'GHG Protocol Land Sector',
      status: 'active',
      issuedDate: '2024-04-30',
      areaHa: 17000,
    },
    {
      id: 'CI-ESP-SOI-2024-001',
      principle: 'soil',
      statement: 'SOC baseline 9.8 tC/ha · 6 strata sampled · calcareous Mediterranean profile',
      evidenceMethod: 'LECO combustion analysis · 36 GPS cores · 0–30 cm depth',
      alignmentStandard: 'Verra VM0042',
      status: 'active',
      issuedDate: '2024-04-30',
      areaHa: 9000,
    },
    {
      id: 'CI-ESP-WAT-2024-001',
      principle: 'water',
      statement: 'Targeted grazing improved spring recharge 14% across 3 karst catchments',
      evidenceMethod: 'Piezometer network · spring flow gauging · precipitation-normalised analysis',
      alignmentStandard: 'Verra W+',
      status: 'active',
      issuedDate: '2024-04-30',
      areaHa: 8500,
    },
    {
      id: 'CI-ESP-BIO-2024-001',
      principle: 'biodiversity',
      statement: '17,000 ha Iberian scrubland under conservation co-management — Iberian lynx habitat',
      evidenceMethod: 'Fundación Global Nature species surveys · camera traps · scrub structure transects',
      alignmentStandard: 'TNFD / SBTN',
      status: 'active',
      issuedDate: '2024-04-30',
      areaHa: 17000,
    },
    {
      id: 'CI-ESP-LIV-2024-001',
      principle: 'livelihoods',
      statement: '62 goat farmers receiving 12% leather premium via certified supply chain',
      evidenceMethod: 'Tannery purchase records · farmer income surveys · certification audit trail',
      alignmentStandard: 'SDG 1.4 / SDG 2.3',
      status: 'active',
      issuedDate: '2024-04-30',
      areaHa: 9000,
    },
    {
      id: 'CI-ESP-AWL-2024-001',
      principle: 'animal_welfare',
      statement: 'Spanish Merino goat welfare standards applied across 17,000 ha — free-range certified',
      evidenceMethod: 'Veterinary inspection records · stocking density GPS logs · five-freedoms audit',
      alignmentStandard: 'Five Freedoms Framework',
      status: 'active',
      issuedDate: '2024-04-30',
      areaHa: 17000,
    },
  ],
};

const argentinaPatagoniaClaims: ProjectClaims = {
  projectId: 'argentina-patagonia-wool',
  claims: [
    {
      id: 'CI-PAT-CLI-2024-001',
      principle: 'climate',
      statement: '300,000 ha Patagonian steppe under Wildlife Friendly-certified grazing management',
      evidenceMethod: 'ERA5 climate data · MODIS land cover · 5yr SOC trajectory model',
      alignmentStandard: 'GHG Protocol Land Sector',
      status: 'active',
      issuedDate: '2024-05-20',
      areaHa: 300000,
    },
    {
      id: 'CI-PAT-SOI-2024-001',
      principle: 'soil',
      statement: 'SOC baseline 8.6 tC/ha · 9 strata sampled · Patagonian coarse-sandy profile',
      evidenceMethod: 'Elemental analyser · GPS composite cores · 0–40 cm depth · 3yr repeat',
      alignmentStandard: 'Verra VM0042',
      status: 'active',
      issuedDate: '2024-05-20',
      areaHa: 150000,
    },
    {
      id: 'CI-PAT-WAT-2024-001',
      principle: 'water',
      statement: 'Riparian exclusion fencing restored 210 km of Patagonian stream margins',
      evidenceMethod: 'GIS riparian mapping · vegetation cover transects · seasonal flow monitoring',
      alignmentStandard: 'Verra W+',
      status: 'active',
      issuedDate: '2024-05-20',
      areaHa: 120000,
    },
    {
      id: 'CI-PAT-BIO-2024-001',
      principle: 'biodiversity',
      statement: '300,000 ha Patagonian steppe under co-management — Andean cat and guanaco recovering',
      evidenceMethod: 'WCS camera trap network · guanaco population transects · puma-prey ratio index',
      alignmentStandard: 'TNFD / SBTN',
      status: 'active',
      issuedDate: '2024-05-20',
      areaHa: 300000,
    },
    {
      id: 'CI-PAT-LIV-2024-001',
      principle: 'livelihoods',
      statement: '180 ranchers earning 15% merino premium via Wildlife Friendly certification',
      evidenceMethod: 'WFEN farm income surveys · offtake price records · certification audit',
      alignmentStandard: 'SDG 1.4 / SDG 2.3',
      status: 'active',
      issuedDate: '2024-05-20',
      areaHa: 160000,
    },
    {
      id: 'CI-PAT-AWL-2024-001',
      principle: 'animal_welfare',
      statement: 'Merino mulesing-free standard applied across 300,000 ha — WFEN certified',
      evidenceMethod: 'WFEN annual farm audits · veterinary records · wool clip documentation',
      alignmentStandard: 'Five Freedoms Framework',
      status: 'active',
      issuedDate: '2024-05-20',
      areaHa: 300000,
    },
  ],
};

const franceWoolClaims: ProjectClaims = {
  projectId: 'france-wool',
  claims: [
    {
      id: 'CI-FRA-CLI-2024-001',
      principle: 'climate',
      statement: '8,000 ha Pyrenean upland under regenerative sheep grazing — pasture carbon stable',
      evidenceMethod: 'ERA5 regional climate · Sentinel-2 biomass index · 4yr NDVI baseline',
      alignmentStandard: 'GHG Protocol Land Sector',
      status: 'active',
      issuedDate: '2024-04-16',
      areaHa: 8000,
    },
    {
      id: 'CI-FRA-SOI-2024-001',
      principle: 'soil',
      statement: 'SOC baseline 28.3 tC/ha · 7 strata · alpine silty-clay upland profile',
      evidenceMethod: 'Walkley-Black oxidation · 48 GPS cores · 0–30 cm · Epiterre field team',
      alignmentStandard: 'Verra VM0042',
      status: 'active',
      issuedDate: '2024-04-16',
      areaHa: 4500,
    },
    {
      id: 'CI-FRA-WAT-2024-001',
      principle: 'water',
      statement: 'High-altitude transhumance reduced summer stream sedimentation 19% on 12 tributaries',
      evidenceMethod: 'OFB turbidity monitoring · seasonal sampling · GIS watershed analysis',
      alignmentStandard: 'Verra W+',
      status: 'active',
      issuedDate: '2024-04-16',
      areaHa: 4000,
    },
    {
      id: 'CI-FRA-BIO-2024-001',
      principle: 'biodiversity',
      statement: '8,000 ha Pyrenean grassland under conservation grazing — golden eagle nesting confirmed',
      evidenceMethod: 'LPO bird surveys · botanist floristic transects · roe deer density index',
      alignmentStandard: 'TNFD / SBTN',
      status: 'active',
      issuedDate: '2024-04-16',
      areaHa: 8000,
    },
    {
      id: 'CI-FRA-LIV-2024-001',
      principle: 'livelihoods',
      statement: '38 Occitanie sheep farmers receiving 11% wool premium via local mill contracts',
      evidenceMethod: 'Epiterre cooperative records · mill purchase agreements · farm income comparison',
      alignmentStandard: 'SDG 1.4 / SDG 2.3',
      status: 'active',
      issuedDate: '2024-04-16',
      areaHa: 4500,
    },
    {
      id: 'CI-FRA-AWL-2024-001',
      principle: 'animal_welfare',
      statement: 'Merino sheep welfare protocols applied — transhumance routes preserved on 8,000 ha',
      evidenceMethod: 'Veterinary seasonal inspections · flock density logs · transhumance route mapping',
      alignmentStandard: 'Five Freedoms Framework',
      status: 'active',
      issuedDate: '2024-04-16',
      areaHa: 8000,
    },
  ],
};

const southAfricaWoolClaims: ProjectClaims = {
  projectId: 'south-africa-wool',
  claims: [
    {
      id: 'CI-ZAF-CLI-2024-001',
      principle: 'climate',
      statement: '11,000 ha Eastern Cape Karoo under holistic planned grazing — bush encroachment reversed',
      evidenceMethod: 'Sentinel-2 woody cover change · ERA5 rainfall normalisation · 5yr NDVI baseline',
      alignmentStandard: 'GHG Protocol Land Sector',
      status: 'active',
      issuedDate: '2024-05-07',
      areaHa: 11000,
    },
    {
      id: 'CI-ZAF-SOI-2024-001',
      principle: 'soil',
      statement: 'SOC baseline 6.4 tC/ha · 8 strata · Karoo shallow-rocky profile · 3yr repeat',
      evidenceMethod: 'Dry combustion elemental analyser · 60 GPS cores · Conservation SA field team',
      alignmentStandard: 'Verra VM0042',
      status: 'active',
      issuedDate: '2024-05-07',
      areaHa: 6000,
    },
    {
      id: 'CI-ZAF-WAT-2024-001',
      principle: 'water',
      statement: 'Livestock exclusion improved 4 seasonal stream margins — infiltration up 17%',
      evidenceMethod: 'Infiltrometer field tests · streambank vegetation transects · rainfall-adjusted analysis',
      alignmentStandard: 'Verra W+',
      status: 'active',
      issuedDate: '2024-05-07',
      areaHa: 5500,
    },
    {
      id: 'CI-ZAF-BIO-2024-001',
      principle: 'biodiversity',
      statement: '11,000 ha Karoo biome under conservation co-management — riverine rabbit habitat',
      evidenceMethod: 'Conservation SA biodiversity surveys · raptor nest monitoring · veld condition index',
      alignmentStandard: 'TNFD / SBTN',
      status: 'active',
      issuedDate: '2024-05-07',
      areaHa: 11000,
    },
    {
      id: 'CI-ZAF-LIV-2024-001',
      principle: 'livelihoods',
      statement: '280 communal herders earning 9% BKB wool premium via grading programme',
      evidenceMethod: 'BKB wool clip records · herder household income surveys · grading improvement logs',
      alignmentStandard: 'SDG 1.4 / SDG 2.3',
      status: 'active',
      issuedDate: '2024-05-07',
      areaHa: 6000,
    },
    {
      id: 'CI-ZAF-AWL-2024-001',
      principle: 'animal_welfare',
      statement: 'Merino welfare standards applied across 11,000 ha — no mulesing, RWS-aligned',
      evidenceMethod: 'Annual veterinary audits · shearing records · stocking rate GPS monitoring',
      alignmentStandard: 'Five Freedoms Framework',
      status: 'active',
      issuedDate: '2024-05-07',
      areaHa: 11000,
    },
  ],
};

// ── 2023 Grant Cycle — climate/soil/livelihoods active; water/bio/welfare draft ─

const ugandaCottonClaims: ProjectClaims = {
  projectId: 'uganda-cotton',
  claims: [
    {
      id: 'CI-UGA-CLI-2024-001',
      principle: 'climate',
      statement: '38,000 ha Kidepo restoration reducing land degradation pressure on wildlife corridor',
      evidenceMethod: 'Global Forest Watch alerts · Landsat deforestation proxy · 3yr baseline',
      alignmentStandard: 'GHG Protocol Land Sector',
      status: 'active',
      issuedDate: '2024-09-04',
      areaHa: 38000,
    },
    {
      id: 'CI-UGA-SOI-2024-001',
      principle: 'soil',
      statement: 'SOC baseline 14.7 tC/ha · 6 strata sampled · East African red clay loam profile',
      evidenceMethod: 'Walkley-Black lab analysis · AWF field team GPS cores · 0–30 cm depth',
      alignmentStandard: 'Verra VM0042',
      status: 'active',
      issuedDate: '2024-09-04',
      areaHa: 3500,
    },
    {
      id: 'CI-UGA-WAT-2024-001',
      principle: 'water',
      statement: 'Conservation tillage reduced runoff 24% across 3,500 ha cotton production area',
      evidenceMethod: 'Runoff plots · farmer practice surveys · seasonal rainfall correction',
      alignmentStandard: 'Verra W+',
      status: 'draft',
      issuedDate: null,
      areaHa: 3500,
    },
    {
      id: 'CI-UGA-BIO-2024-001',
      principle: 'biodiversity',
      statement: '38,000 ha Kidepo buffer zone under conservation co-management — lion conflict reduced',
      evidenceMethod: 'AWF conflict incident database · camera traps · livestock mortality records',
      alignmentStandard: 'TNFD / SBTN',
      status: 'draft',
      issuedDate: null,
      areaHa: 38000,
    },
    {
      id: 'CI-UGA-LIV-2024-001',
      principle: 'livelihoods',
      statement: '2,000 cotton farmers with improved yields — 8% income uplift documented 2023',
      evidenceMethod: 'Baseline/endline household surveys · cotton gin records · AWF M&E reports',
      alignmentStandard: 'SDG 1.4 / SDG 2.3',
      status: 'active',
      issuedDate: '2024-09-04',
      areaHa: 6000,
    },
    {
      id: 'CI-UGA-AWL-2024-001',
      principle: 'animal_welfare',
      statement: 'Soil biota index 6.1/10 — pesticide-free cotton on 6,000 ha confirmed',
      evidenceMethod: 'Soil mesofauna counts · pesticide register audit · AWF field verification',
      alignmentStandard: 'Pollinator Health Standard',
      status: 'draft',
      issuedDate: null,
      areaHa: 6000,
    },
  ],
};

const indiaCottonWfenClaims: ProjectClaims = {
  projectId: 'india-cotton-wfen',
  claims: [
    {
      id: 'CI-IND-T-CLI-2024-001',
      principle: 'climate',
      statement: '5,000 ha tiger corridor under agroforestry cotton — tree cover expanding',
      evidenceMethod: 'Sentinel-2 canopy cover change · WFEN field surveys · 2yr baseline',
      alignmentStandard: 'GHG Protocol Land Sector',
      status: 'active',
      issuedDate: '2024-10-10',
      areaHa: 5000,
    },
    {
      id: 'CI-IND-T-SOI-2024-001',
      principle: 'soil',
      statement: 'SOC baseline 13.9 tC/ha · 7 strata sampled · Vidarbha black cotton soil profile',
      evidenceMethod: 'NIRS spectroscopy · 42 GPS cores · 0–30 cm depth · WWF-India lab',
      alignmentStandard: 'Verra VM0042',
      status: 'active',
      issuedDate: '2024-10-10',
      areaHa: 2800,
    },
    {
      id: 'CI-IND-T-WAT-2024-001',
      principle: 'water',
      statement: 'Farm pond harvesting installed on 400 farms — groundwater recharge index improving',
      evidenceMethod: 'Piezometer network · seasonal water table surveys · satellite ET mapping',
      alignmentStandard: 'Verra W+',
      status: 'draft',
      issuedDate: null,
      areaHa: 2800,
    },
    {
      id: 'CI-IND-T-BIO-2024-001',
      principle: 'biodiversity',
      statement: '5,000 ha Pench-Satpura corridor cotton farmed pesticide-reduced — tiger sign present',
      evidenceMethod: 'WWF-India camera traps · mammal track surveys · acoustic bat monitoring',
      alignmentStandard: 'TNFD / SBTN',
      status: 'draft',
      issuedDate: null,
      areaHa: 5000,
    },
    {
      id: 'CI-IND-T-LIV-2024-001',
      principle: 'livelihoods',
      statement: '900 women cotton farmers accessing certified markets — 13% income premium',
      evidenceMethod: 'WFEN gender-disaggregated income surveys · offtake records · certification audit',
      alignmentStandard: 'SDG 1.4 / SDG 2.3',
      status: 'active',
      issuedDate: '2024-10-10',
      areaHa: 5000,
    },
    {
      id: 'CI-IND-T-AWL-2024-001',
      principle: 'animal_welfare',
      statement: 'Pollinator health index 6.8/10 — neonicotinoid-free on 5,000 ha documented',
      evidenceMethod: 'Bee colony health surveys · pesticide register verification · WFEN field audits',
      alignmentStandard: 'Pollinator Health Standard',
      status: 'draft',
      issuedDate: null,
      areaHa: 5000,
    },
  ],
};

const pakistanCottonClaims: ProjectClaims = {
  projectId: 'pakistan-cotton',
  claims: [
    {
      id: 'CI-PAK-CLI-2024-001',
      principle: 'climate',
      statement: '15,000 ha Punjab/Sindh cotton under reduced tillage — synthetic input drawdown',
      evidenceMethod: 'Sentinel-2 crop mapping · IPCC emission factor reduction model · 2yr baseline',
      alignmentStandard: 'GHG Protocol Land Sector',
      status: 'active',
      issuedDate: '2024-08-22',
      areaHa: 15000,
    },
    {
      id: 'CI-PAK-SOI-2024-001',
      principle: 'soil',
      statement: 'SOC baseline 8.3 tC/ha · 6 strata sampled · Indus alluvial loam profile',
      evidenceMethod: 'Walkley-Black analysis · GPS composite cores · 0–30 cm depth · 2yr series',
      alignmentStandard: 'Verra VM0042',
      status: 'active',
      issuedDate: '2024-08-22',
      areaHa: 8000,
    },
    {
      id: 'CI-PAK-WAT-2024-001',
      principle: 'water',
      statement: 'Laser land levelling reduced irrigation water application 28% on 8,000 ha',
      evidenceMethod: 'Canal outlet flow records · farmer irrigation logs · satellite ET estimation',
      alignmentStandard: 'Verra W+',
      status: 'draft',
      issuedDate: null,
      areaHa: 8000,
    },
    {
      id: 'CI-PAK-BIO-2024-001',
      principle: 'biodiversity',
      statement: '15,000 ha Indus plain cotton — pesticide reduction enabling invertebrate recovery',
      evidenceMethod: 'Baseline invertebrate transects · pesticide input records · farmer surveys',
      alignmentStandard: 'TNFD / SBTN',
      status: 'draft',
      issuedDate: null,
      areaHa: 15000,
    },
    {
      id: 'CI-PAK-LIV-2024-001',
      principle: 'livelihoods',
      statement: 'Smallholder farmers accessing certified better cotton markets — yield stability improved',
      evidenceMethod: 'Ginning factory records · household yield surveys · market price comparison',
      alignmentStandard: 'SDG 1.4 / SDG 2.3',
      status: 'active',
      issuedDate: '2024-08-22',
      areaHa: 15000,
    },
    {
      id: 'CI-PAK-AWL-2024-001',
      principle: 'animal_welfare',
      statement: 'Soil health index 5.9/10 — IPM adoption reducing pesticide loading on 15,000 ha',
      evidenceMethod: 'IPM training records · pesticide purchase audit · soil invertebrate monitoring',
      alignmentStandard: 'Pollinator Health Standard',
      status: 'draft',
      issuedDate: null,
      areaHa: 15000,
    },
  ],
};

// ── 2025 New Projects — all claims pending ───────────────────────────────────

const turkeyCottonClaims: ProjectClaims = {
  projectId: 'turkey-cotton',
  claims: [
    {
      id: 'CI-TUR-CLI-2025-001',
      principle: 'climate',
      statement: '10,000 ha SE Anatolia cotton — baseline emissions inventory initiated',
      evidenceMethod: 'ERA5 climate baseline · IPCC Tier 1 inventory · Sentinel-2 crop mapping',
      alignmentStandard: 'GHG Protocol Land Sector',
      status: 'pending',
      issuedDate: null,
      areaHa: 10000,
    },
    {
      id: 'CI-TUR-SOI-2025-001',
      principle: 'soil',
      statement: 'SOC baseline survey planned — Harran plain clay-loam soil characterisation',
      evidenceMethod: 'GPS composite core sampling · Walkley-Black protocol · 0–30 cm depth',
      alignmentStandard: 'Verra VM0042',
      status: 'pending',
      issuedDate: null,
      areaHa: 5500,
    },
    {
      id: 'CI-TUR-WAT-2025-001',
      principle: 'water',
      statement: 'Irrigation efficiency baseline survey — Harran canal system water use mapping',
      evidenceMethod: 'Flow meter installation · satellite ET calibration · farmer irrigation logs',
      alignmentStandard: 'Verra W+',
      status: 'pending',
      issuedDate: null,
      areaHa: 5500,
    },
    {
      id: 'CI-TUR-BIO-2025-001',
      principle: 'biodiversity',
      statement: '10,000 ha SE Anatolia — biodiversity baseline survey in design phase',
      evidenceMethod: 'Pollinator transects · bird point counts · invertebrate sampling design',
      alignmentStandard: 'TNFD / SBTN',
      status: 'pending',
      issuedDate: null,
      areaHa: 10000,
    },
    {
      id: 'CI-TUR-LIV-2025-001',
      principle: 'livelihoods',
      statement: 'Smallholder farmer baseline income survey in progress — 2025 cohort',
      evidenceMethod: 'Household survey design · census cross-reference · ginning cooperative records',
      alignmentStandard: 'SDG 1.4 / SDG 2.3',
      status: 'pending',
      issuedDate: null,
      areaHa: 10000,
    },
    {
      id: 'CI-TUR-AWL-2025-001',
      principle: 'animal_welfare',
      statement: 'Soil biota baseline planned — pesticide audit framework under development',
      evidenceMethod: 'Soil invertebrate sampling design · pesticide register protocol · farmer training',
      alignmentStandard: 'Pollinator Health Standard',
      status: 'pending',
      issuedDate: null,
      areaHa: 10000,
    },
  ],
};

const australiaWoolClaims: ProjectClaims = {
  projectId: 'australia-wool',
  claims: [
    {
      id: 'CI-AUS-CLI-2025-001',
      principle: 'climate',
      statement: '20,000 ha NSW/Victoria wool country — carbon baseline methodology in design',
      evidenceMethod: 'ERA5 climate baseline · MODIS land cover · FullCAM model adaptation',
      alignmentStandard: 'GHG Protocol Land Sector',
      status: 'pending',
      issuedDate: null,
      areaHa: 20000,
    },
    {
      id: 'CI-AUS-SOI-2025-001',
      principle: 'soil',
      statement: 'SOC baseline survey planned — Tablelands red-brown earth soil characterisation',
      evidenceMethod: 'Dry combustion elemental analyser · GPS core network · 0–30 cm depth',
      alignmentStandard: 'Verra VM0042',
      status: 'pending',
      issuedDate: null,
      areaHa: 10000,
    },
    {
      id: 'CI-AUS-WAT-2025-001',
      principle: 'water',
      statement: 'Riparian condition baseline mapping — Murray-Darling tributary health survey',
      evidenceMethod: 'AusRivAS protocol · vegetation transects · seasonal flow gauging network',
      alignmentStandard: 'Verra W+',
      status: 'pending',
      issuedDate: null,
      areaHa: 10000,
    },
    {
      id: 'CI-AUS-BIO-2025-001',
      principle: 'biodiversity',
      statement: '20,000 ha grassy woodland — threatened species baseline survey in design',
      evidenceMethod: 'Atlas of Living Australia baseline · acoustic bat monitoring · flora transects',
      alignmentStandard: 'TNFD / SBTN',
      status: 'pending',
      issuedDate: null,
      areaHa: 20000,
    },
    {
      id: 'CI-AUS-LIV-2025-001',
      principle: 'livelihoods',
      statement: 'Merino wool farmer income baseline survey — RWS certification pathway mapping',
      evidenceMethod: 'Farm income surveys · wool broker records · certification pathway assessment',
      alignmentStandard: 'SDG 1.4 / SDG 2.3',
      status: 'pending',
      issuedDate: null,
      areaHa: 20000,
    },
    {
      id: 'CI-AUS-AWL-2025-001',
      principle: 'animal_welfare',
      statement: 'Merino welfare protocol baseline — mulesing-free transition pathway under assessment',
      evidenceMethod: 'RWS farm audit protocol · veterinary records template · welfare KPI framework',
      alignmentStandard: 'Five Freedoms Framework',
      status: 'pending',
      issuedDate: null,
      areaHa: 20000,
    },
  ],
};

const nzWoolClaims: ProjectClaims = {
  projectId: 'nz-wool',
  claims: [
    {
      id: 'CI-NZL-CLI-2025-001',
      principle: 'climate',
      statement: '15,000 ha Canterbury/Otago high country — methane baseline inventory in design',
      evidenceMethod: 'ERA5 climate baseline · OVERSEER nutrient model · Sentinel-2 land cover',
      alignmentStandard: 'GHG Protocol Land Sector',
      status: 'pending',
      issuedDate: null,
      areaHa: 15000,
    },
    {
      id: 'CI-NZL-SOI-2025-001',
      principle: 'soil',
      statement: 'SOC baseline survey planned — South Island high-country brown soil characterisation',
      evidenceMethod: 'Loss-on-ignition / dry combustion · GPS core network · 0–30 cm depth',
      alignmentStandard: 'Verra VM0042',
      status: 'pending',
      issuedDate: null,
      areaHa: 7500,
    },
    {
      id: 'CI-NZL-WAT-2025-001',
      principle: 'water',
      statement: 'Braided river catchment baseline — riparian fencing feasibility under assessment',
      evidenceMethod: 'Freshwater Improvement Fund protocols · turbidity logger network design',
      alignmentStandard: 'Verra W+',
      status: 'pending',
      issuedDate: null,
      areaHa: 7500,
    },
    {
      id: 'CI-NZL-BIO-2025-001',
      principle: 'biodiversity',
      statement: '15,000 ha tussock grassland — threatened native bird baseline survey in design',
      evidenceMethod: 'Five-minute bird counts · DOC threatened species database · habitat mapping',
      alignmentStandard: 'TNFD / SBTN',
      status: 'pending',
      issuedDate: null,
      areaHa: 15000,
    },
    {
      id: 'CI-NZL-LIV-2025-001',
      principle: 'livelihoods',
      statement: 'High-country merino farmer income baseline — ZQ Merino certification pathway',
      evidenceMethod: 'Farm income surveys · wool auction records · ZQ programme documentation',
      alignmentStandard: 'SDG 1.4 / SDG 2.3',
      status: 'pending',
      issuedDate: null,
      areaHa: 15000,
    },
    {
      id: 'CI-NZL-AWL-2025-001',
      principle: 'animal_welfare',
      statement: 'Merino welfare baseline — ZQ Merino five-freedoms audit protocol in design',
      evidenceMethod: 'ZQ audit framework · veterinary records protocol · stocking density mapping',
      alignmentStandard: 'Five Freedoms Framework',
      status: 'pending',
      issuedDate: null,
      areaHa: 15000,
    },
  ],
};

// ── Exported record ───────────────────────────────────────────────────────────

export const projectClaims: Record<string, ProjectClaims> = {
  'mongolia-cashmere': mongoliaClaims,
  'india-cotton-oca': indiaOcaClaims,
  'argentina-leather': argentinaLeatherClaims,
  'spain-goat-leather': spainGoatClaims,
  'argentina-patagonia-wool': argentinaPatagoniaClaims,
  'france-wool': franceWoolClaims,
  'south-africa-wool': southAfricaWoolClaims,
  'uganda-cotton': ugandaCottonClaims,
  'india-cotton-wfen': indiaCottonWfenClaims,
  'pakistan-cotton': pakistanCottonClaims,
  'turkey-cotton': turkeyCottonClaims,
  'australia-wool': australiaWoolClaims,
  'nz-wool': nzWoolClaims,
};
