import { Project, FundSummary, DataCompleteness } from '../types';

export const projects: Project[] = [
  {
    id: 'mongolia-cashmere',
    name: 'Sustainable Cashmere Landscapes',
    grantee: 'The Good Growth Company',
    country: 'Mongolia',
    region: 'Central Mongolia',
    commodity: 'cashmere',
    hectares: 342000,
    hectaresType: 'mixed',
    beneficiaries: null,
    lat: 47.5,
    lng: 106.9,
    yearJoined: 2021,
    grantCycle: '2021',
    status: 'active',
    description:
      'Working with nomadic herders to implement sustainable cashmere grazing practices across degraded Mongolian grasslands. Satellite data informs herd allocation decisions ahead of winter.',
  },
  {
    id: 'india-cotton-oca',
    name: 'Organic Cotton Transition',
    grantee: 'Organic Cotton Accelerator (OCA)',
    country: 'India',
    region: 'Maharashtra / Madhya Pradesh',
    commodity: 'cotton',
    hectares: 53500,
    hectaresType: 'direct',
    beneficiaries: 50000,
    lat: 21.1,
    lng: 76.5,
    yearJoined: 2021,
    grantCycle: '2021',
    status: 'active',
    description:
      'Supporting 50,000 smallholder farmers in transitioning to organic cotton. Female smallholders have earned organic certification with 10% price premiums.',
  },
  {
    id: 'argentina-leather',
    name: 'Gran Chaco Sustainable Leather',
    grantee: 'Solidaridad',
    country: 'Argentina',
    region: 'Gran Chaco',
    commodity: 'leather',
    hectares: 120000,
    hectaresType: 'direct',
    beneficiaries: null,
    lat: -24.5,
    lng: -61.0,
    yearJoined: 2021,
    grantCycle: '2021',
    status: 'active',
    description:
      'Partnering with Indigenous producers in the Gran Chaco to develop sustainable cowhide leather supply chains. NOTE: Leather dropped from 2025 eligible commodities.',
  },
  {
    id: 'spain-goat-leather',
    name: 'Mediterranean Goat Leather',
    grantee: 'Fundación Global Nature',
    country: 'Spain',
    region: 'Multiple regions',
    commodity: 'leather',
    hectares: 17000,
    hectaresType: 'direct',
    beneficiaries: null,
    lat: 39.5,
    lng: -2.5,
    yearJoined: 2021,
    grantCycle: '2021',
    status: 'active',
    description:
      'Regenerative goat leather production across three Spanish regions. NOTE: Leather dropped from 2025 eligible commodities.',
  },
  {
    id: 'argentina-patagonia-wool',
    name: 'Patagonian Merino Wool & Mohair',
    grantee: 'WCS & Wildlife-Friendly Enterprise Network',
    country: 'Argentina',
    region: 'Patagonia',
    commodity: 'wool',
    hectares: 300000,
    hectaresType: 'direct',
    beneficiaries: null,
    lat: -44.0,
    lng: -70.0,
    yearJoined: 2021,
    grantCycle: '2021',
    status: 'active',
    description:
      'Wildlife Friendly-certified merino wool and mohair commanding 15% price premium. Documented recovery of threatened Andean cat and guanaco populations.',
  },
  {
    id: 'france-wool',
    name: 'Midi-Pyrénées Wool & Sheep Leather',
    grantee: 'Epiterre',
    country: 'France',
    region: 'Midi-Pyrénées / Occitanie',
    commodity: 'wool',
    hectares: 8000,
    hectaresType: 'direct',
    beneficiaries: null,
    lat: 43.3,
    lng: 1.4,
    yearJoined: 2021,
    grantCycle: '2021',
    status: 'active',
    description:
      'Regional wool and sheep leather production in southern France using regenerative grazing practices.',
  },
  {
    id: 'south-africa-wool',
    name: 'Eastern Cape Sheep Wool',
    grantee: 'Conservation South Africa',
    country: 'South Africa',
    region: 'Eastern Cape',
    commodity: 'wool',
    hectares: 11000,
    hectaresType: 'direct',
    beneficiaries: 280,
    lat: -32.0,
    lng: 27.5,
    yearJoined: 2021,
    grantCycle: '2021',
    status: 'active',
    description:
      'Working with communal herders on sheep wool production. BKB is the dominant regional broker marketing 62% of SA wool clip.',
  },
  {
    id: 'uganda-cotton',
    name: 'Kidepo Landscape Cotton',
    grantee: 'African Wildlife Foundation / DADO',
    country: 'Uganda',
    region: 'Kidepo Landscape',
    commodity: 'cotton',
    hectares: 6000,
    hectaresType: 'direct',
    beneficiaries: 2000,
    lat: 3.5,
    lng: 33.8,
    yearJoined: 2023,
    grantCycle: '2023',
    status: 'active',
    description:
      '2,000+ cotton farmers on 6,000 ha production with 32,000 ha restoration. Improved cotton yields and reduced human-wildlife conflict documented.',
  },
  {
    id: 'india-cotton-wfen',
    name: 'Tiger Corridor Cotton',
    grantee: 'WFEN with WWF-India',
    country: 'India',
    region: 'Pench-Satpura-Melghat Corridor',
    commodity: 'cotton',
    hectares: 5000,
    hectaresType: 'direct',
    beneficiaries: 900,
    lat: 21.7,
    lng: 78.5,
    yearJoined: 2023,
    grantCycle: '2023',
    status: 'active',
    description:
      '900 women cotton farmers in the Pench-Satpura-Melghat tiger corridor. Integrating wildlife conservation with cotton production.',
  },
  {
    id: 'pakistan-cotton',
    name: 'Pakistan Cotton Regeneration',
    grantee: 'TBD Partner',
    country: 'Pakistan',
    region: 'Punjab / Sindh',
    commodity: 'cotton',
    hectares: 15000,
    hectaresType: 'direct',
    beneficiaries: null,
    lat: 28.5,
    lng: 69.5,
    yearJoined: 2023,
    grantCycle: '2023',
    status: 'active',
    description: 'Cotton regeneration project in Pakistan. Details limited in public sources.',
  },
  {
    id: 'turkey-cotton',
    name: 'Türkiye Cotton Transition',
    grantee: 'TBD Partner',
    country: 'Türkiye',
    region: 'Southeastern Anatolia',
    commodity: 'cotton',
    hectares: 10000,
    hectaresType: 'direct',
    beneficiaries: null,
    lat: 37.5,
    lng: 38.5,
    yearJoined: 2025,
    grantCycle: '2025',
    status: 'new',
    description:
      'New 2025 geography for cotton. Brazil and Türkiye added as eligible cotton geographies in 2025 cycle.',
  },
  {
    id: 'australia-wool',
    name: 'Australia Wool Regeneration',
    grantee: 'TBD Partner',
    country: 'Australia',
    region: 'New South Wales / Victoria',
    commodity: 'wool',
    hectares: 20000,
    hectaresType: 'direct',
    beneficiaries: null,
    lat: -33.5,
    lng: 148.0,
    yearJoined: 2025,
    grantCycle: '2025',
    status: 'new',
    description:
      'New 2025 geography. Australia and New Zealand opened for wool in 2025 cycle.',
  },
  {
    id: 'nz-wool',
    name: 'New Zealand Wool Regeneration',
    grantee: 'TBD Partner',
    country: 'New Zealand',
    region: 'Canterbury / Otago',
    commodity: 'wool',
    hectares: 15000,
    hectaresType: 'direct',
    beneficiaries: null,
    lat: -44.5,
    lng: 170.5,
    yearJoined: 2025,
    grantCycle: '2025',
    status: 'new',
    description:
      'New 2025 geography. Australia and New Zealand opened for wool in 2025 cycle.',
  },
];

export const fundSummary: FundSummary = {
  totalHectares: 1100000,
  directHectares: 845000,
  indirectHectares: 267000,
  totalProjects: 13,
  totalCountries: 8,
  totalBeneficiaries: 105000,
  launchYear: 2021,
  targetHectares: 1000000,
  commodities: ['cotton', 'wool', 'cashmere', 'leather'],
  activeCommodities2025: ['cotton', 'wool', 'cashmere'],
  brandPartners: ['Kering', 'Inditex'],
  grantRange2024: { min: 120000, max: 620000 },
  grantRange2025: { min: 300000, max: 600000 },
};

// Simulated data completeness — most projects have partial/missing data (per Jim's honesty)
export const dataCompleteness: Record<string, DataCompleteness> = {
  'mongolia-cashmere': {
    soil: 'partial',
    biodiversity: 'missing',
    water: 'partial',
    livelihoods: 'partial',
    score: 42,
    lastUpdated: '2024-09-15',
  },
  'india-cotton-oca': {
    soil: 'complete',
    biodiversity: 'complete',
    water: 'missing',
    livelihoods: 'complete',
    score: 78,
    lastUpdated: '2024-11-20',
  },
  'argentina-leather': {
    soil: 'partial',
    biodiversity: 'partial',
    water: 'missing',
    livelihoods: 'missing',
    score: 31,
    lastUpdated: '2024-06-10',
  },
  'spain-goat-leather': {
    soil: 'missing',
    biodiversity: 'partial',
    water: 'missing',
    livelihoods: 'missing',
    score: 18,
    lastUpdated: '2024-03-22',
  },
  'argentina-patagonia-wool': {
    soil: 'complete',
    biodiversity: 'complete',
    water: 'partial',
    livelihoods: 'partial',
    score: 72,
    lastUpdated: '2024-10-05',
  },
  'france-wool': {
    soil: 'partial',
    biodiversity: 'missing',
    water: 'missing',
    livelihoods: 'partial',
    score: 28,
    lastUpdated: '2024-07-18',
  },
  'south-africa-wool': {
    soil: 'partial',
    biodiversity: 'partial',
    water: 'partial',
    livelihoods: 'complete',
    score: 55,
    lastUpdated: '2024-08-30',
  },
  'uganda-cotton': {
    soil: 'partial',
    biodiversity: 'partial',
    water: 'missing',
    livelihoods: 'partial',
    score: 38,
    lastUpdated: '2024-09-01',
  },
  'india-cotton-wfen': {
    soil: 'missing',
    biodiversity: 'partial',
    water: 'missing',
    livelihoods: 'partial',
    score: 25,
    lastUpdated: '2024-05-14',
  },
  'pakistan-cotton': {
    soil: 'missing',
    biodiversity: 'missing',
    water: 'missing',
    livelihoods: 'missing',
    score: 8,
    lastUpdated: null,
  },
  'turkey-cotton': {
    soil: 'missing',
    biodiversity: 'missing',
    water: 'missing',
    livelihoods: 'missing',
    score: 0,
    lastUpdated: null,
  },
  'australia-wool': {
    soil: 'missing',
    biodiversity: 'missing',
    water: 'missing',
    livelihoods: 'missing',
    score: 0,
    lastUpdated: null,
  },
  'nz-wool': {
    soil: 'missing',
    biodiversity: 'missing',
    water: 'missing',
    livelihoods: 'missing',
    score: 0,
    lastUpdated: null,
  },
};
