import { Project, FundSummary, DataCompleteness, ProjectNarrative, ProjectBiodiversity, ProjectAnimalWelfare, ProjectLivelihoodContext } from '../types';

export const projects: Project[] = [
  {
    id: 'mongolia-cashmere',
    name: 'Sustainable Cashmere Landscapes',
    grantee: 'The Good Growth Company',
    country: 'Mongolia',
    region: 'Central Mongolia',
    commodity: 'cashmere',
    hectares: 342000,
    hectaresType: 'mixed',
    beneficiaries: null,
    lat: 47.5,
    lng: 106.9,
    yearJoined: 2021,
    grantCycle: '2021',
    status: 'active',
    description:
      'Working with nomadic herders to implement sustainable cashmere grazing practices across degraded Mongolian grasslands. Satellite data informs herd allocation decisions ahead of winter.',
  },
  {
    id: 'india-cotton-oca',
    name: 'Organic Cotton Transition',
    grantee: 'Organic Cotton Accelerator (OCA)',
    country: 'India',
    region: 'Maharashtra / Madhya Pradesh',
    commodity: 'cotton',
    hectares: 53500,
    hectaresType: 'direct',
    beneficiaries: 50000,
    lat: 21.1,
    lng: 76.5,
    yearJoined: 2021,
    grantCycle: '2021',
    status: 'active',
    description:
      'Supporting 50,000 smallholder farmers in transitioning to organic cotton. Female smallholders have earned organic certification with 10% price premiums.',
  },
  {
    id: 'argentina-leather',
    name: 'Gran Chaco Sustainable Leather',
    grantee: 'Solidaridad',
    country: 'Argentina',
    region: 'Gran Chaco',
    commodity: 'leather',
    hectares: 120000,
    hectaresType: 'direct',
    beneficiaries: null,
    lat: -24.5,
    lng: -61.0,
    yearJoined: 2021,
    grantCycle: '2021',
    status: 'active',
    description:
      'Partnering with Indigenous producers in the Gran Chaco to develop sustainable cowhide leather supply chains. NOTE: Leather dropped from 2025 eligible commodities.',
  },
  {
    id: 'spain-goat-leather',
    name: 'Mediterranean Goat Leather',
    grantee: 'Fundaci\u00f3n Global Nature',
    country: 'Spain',
    region: 'Multiple regions',
    commodity: 'leather',
    hectares: 17000,
    hectaresType: 'direct',
    beneficiaries: null,
    lat: 39.5,
    lng: -2.5,
    yearJoined: 2021,
    grantCycle: '2021',
    status: 'active',
    description:
      'Regenerative goat leather production across three Spanish regions. NOTE: Leather dropped from 2025 eligible commodities.',
  },
  {
    id: 'argentina-patagonia-wool',
    name: 'Patagonian Merino Wool & Mohair',
    grantee: 'WCS & Wildlife-Friendly Enterprise Network',
    country: 'Argentina',
    region: 'Patagonia',
    commodity: 'wool',
    hectares: 300000,
    hectaresType: 'direct',
    beneficiaries: null,
    lat: -44.0,
    lng: -70.0,
    yearJoined: 2021,
    grantCycle: '2021',
    status: 'active',
    description:
      'Wildlife Friendly-certified merino wool and mohair commanding 15% price premium. Documented recovery of threatened Andean cat and guanaco populations.',
  },
  {
    id: 'france-wool',
    name: 'Midi-Pyr\u00e9n\u00e9es Wool & Sheep Leather',
    grantee: 'Epiterre',
    country: 'France',
    region: 'Midi-Pyr\u00e9n\u00e9es / Occitanie',
    commodity: 'wool',
    hectares: 8000,
    hectaresType: 'direct',
    beneficiaries: null,
    lat: 43.3,
    lng: 1.4,
    yearJoined: 2021,
    grantCycle: '2021',
    status: 'active',
    description:
      'Regional wool and sheep leather production in southern France using regenerative grazing practices.',
  },
  {
    id: 'south-africa-wool',
    name: 'Eastern Cape Sheep Wool',
    grantee: 'Conservation South Africa',
    country: 'South Africa',
    region: 'Eastern Cape',
    commodity: 'wool',
    hectares: 11000,
    hectaresType: 'direct',
    beneficiaries: 280,
    lat: -32.0,
    lng: 27.5,
    yearJoined: 2021,
    grantCycle: '2021',
    status: 'active',
    description:
      'Working with communal herders on sheep wool production. BKB is the dominant regional broker marketing 62% of SA wool clip.',
  },
  {
    id: 'uganda-cotton',
    name: 'Kidepo Landscape Cotton',
    grantee: 'African Wildlife Foundation / DADO',
    country: 'Uganda',
    region: 'Kidepo Landscape',
    commodity: 'cotton',
    hectares: 6000,
    hectaresType: 'direct',
    beneficiaries: 2000,
    lat: 3.5,
    lng: 33.8,
    yearJoined: 2023,
    grantCycle: '2023',
    status: 'active',
    description:
      '2,000+ cotton farmers on 6,000 ha production with 32,000 ha restoration. Improved cotton yields and reduced human-wildlife conflict documented.',
  },
  {
    id: 'india-cotton-wfen',
    name: 'Tiger Corridor Cotton',
    grantee: 'WFEN with WWF-India',
    country: 'India',
    region: 'Pench-Satpura-Melghat Corridor',
    commodity: 'cotton',
    hectares: 5000,
    hectaresType: 'direct',
    beneficiaries: 900,
    lat: 21.7,
    lng: 78.5,
    yearJoined: 2023,
    grantCycle: '2023',
    status: 'active',
    description:
      '900 women cotton farmers in the Pench-Satpura-Melghat tiger corridor. Integrating wildlife conservation with cotton production.',
  },
  {
    id: 'pakistan-cotton',
    name: 'Pakistan Cotton Regeneration',
    grantee: 'TBD Partner',
    country: 'Pakistan',
    region: 'Punjab / Sindh',
    commodity: 'cotton',
    hectares: 15000,
    hectaresType: 'direct',
    beneficiaries: null,
    lat: 28.5,
    lng: 69.5,
    yearJoined: 2023,
    grantCycle: '2023',
    status: 'active',
    description: 'Cotton regeneration project in Pakistan. Details limited in public sources.',
  },
  {
    id: 'turkey-cotton',
    name: 'T\u00fcrkiye Cotton Transition',
    grantee: 'TBD Partner',
    country: 'T\u00fcrkiye',
    region: 'Southeastern Anatolia',
    commodity: 'cotton',
    hectares: 10000,
    hectaresType: 'direct',
    beneficiaries: null,
    lat: 37.5,
    lng: 38.5,
    yearJoined: 2025,
    grantCycle: '2025',
    status: 'new',
    description:
      'New 2025 geography for cotton. Brazil and T\u00fcrkiye added as eligible cotton geographies in 2025 cycle.',
  },
  {
    id: 'australia-wool',
    name: 'Australia Wool Regeneration',
    grantee: 'TBD Partner',
    country: 'Australia',
    region: 'New South Wales / Victoria',
    commodity: 'wool',
    hectares: 20000,
    hectaresType: 'direct',
    beneficiaries: null,
    lat: -33.5,
    lng: 148.0,
    yearJoined: 2025,
    grantCycle: '2025',
    status: 'new',
    description:
      'New 2025 geography. Australia and New Zealand opened for wool in 2025 cycle.',
  },
  {
    id: 'nz-wool',
    name: 'New Zealand Wool Regeneration',
    grantee: 'TBD Partner',
    country: 'New Zealand',
    region: 'Canterbury / Otago',
    commodity: 'wool',
    hectares: 15000,
    hectaresType: 'direct',
    beneficiaries: null,
    lat: -44.5,
    lng: 170.5,
    yearJoined: 2025,
    grantCycle: '2025',
    status: 'new',
    description:
      'New 2025 geography. Australia and New Zealand opened for wool in 2025 cycle.',
  },
];

// ── Project Narratives ──────────────────────────────────────────────────────

export const projectNarratives: Record<string, ProjectNarrative> = {
  'mongolia-cashmere': {
    overview: 'Working with nomadic herders across Central Mongolia to implement sustainable cashmere production through satellite-informed grazing management and SFA certification. The project addresses the tension between cashmere demand and grassland degradation across 342,000 hectares.',
    objectives: [
      'Reduce pastureland degradation through rotational grazing and rest periods',
      'Improve herder income via quality-based premiums and SFA certification',
      'Establish SOC and vegetation monitoring baselines across project rangeland',
      'Demonstrate scalable cashmere sustainability model for brand sourcing',
    ],
    challenges: [
      'Extreme continental climate with -40\u00b0C winters and summer drought \u2014 monitoring windows are short',
      'Nomadic communities make consistent data collection logistically difficult',
      'Cashmere pricing is volatile and dominated by unprocessed export to China (~80%)',
      'Overgrazing is driven by national herd size policy \u2014 systemic issue beyond project scope',
    ],
    keyResults: [
      'SFA has certified 21,585+ herders across 17 Mongolian provinces',
      'Satellite-informed herd allocation reducing winter dzud mortality risk',
      'First SOC baseline sampling completed across representative strata',
    ],
    currentPhase: 'Year 4 of implementation. Second monitoring cycle underway. Expanding SFA certification reach while establishing long-term vegetation transects.',
    brandPartnerContext: 'Kering sources cashmere for Gucci, Saint Laurent, and Bottega Veneta. Inditex sources for Zara and Massimo Dutti.',
    lastUpdated: '2025-12-01',
  },
  'india-cotton-oca': {
    overview: 'Supporting 50,000 smallholder farmers in Maharashtra and Madhya Pradesh in transitioning to organic cotton production. The project focuses on female farmers, with documented 10% price premiums for organic certification.',
    objectives: [
      'Transition 50,000+ farmers to certified organic cotton production',
      'Increase farmer income through organic price premiums and reduced input costs',
      'Build SOC and biodiversity monitoring capacity at farm cluster level',
      'Demonstrate scalable organic transition model for Indian cotton belt',
    ],
    challenges: [
      'Highly fragmented smallholder landscape \u2014 average farm size under 2 hectares',
      'Monsoon variability creates year-to-year yield uncertainty',
      'Organic certification costs and transition period (3 years) create financial barriers',
      'Data collection across 50,000 dispersed farmers requires mobile-first approach',
    ],
    keyResults: [
      'Female smallholders have earned organic certification with 10% price premiums',
      'Over 50,000 farmers enrolled \u2014 largest organic cotton transition in the fund',
      'Soil health monitoring protocols established across representative farm clusters',
    ],
    currentPhase: 'Year 4. Scaling phase \u2014 expanding enrollment while deepening monitoring on established farms. Working toward landscape-level biodiversity corridor mapping.',
    brandPartnerContext: 'Cotton sourced through OCA network to both Kering and Inditex supply chains. India is the largest cotton geography in the fund.',
    lastUpdated: '2025-12-01',
  },
  'argentina-leather': {
    overview: 'Partnering with Indigenous communities and producers in the Gran Chaco to develop sustainable cowhide leather supply chains. Solidaridad leads implementation across 120,000 hectares of dry forest and savanna landscape.',
    objectives: [
      'Develop traceable sustainable leather sourcing from Gran Chaco rangelands',
      'Support Indigenous producers in accessing premium leather markets',
      'Halt deforestation within project boundaries through sustainable intensification',
      'Build monitoring framework for forest cover and rangeland condition',
    ],
    challenges: [
      'Gran Chaco is one of the world\'s highest deforestation frontiers',
      'Leather dropped from 2025 eligible commodities \u2014 project continuation TBD',
      'Indigenous land tenure complexity affects project boundary definition',
      'Leather supply chains are long and opaque \u2014 traceability is difficult',
    ],
    keyResults: [
      'Sustainable leather protocols established with Solidaridad',
      'Indigenous producer engagement model developed',
      'Satellite-based deforestation monitoring active across project area',
    ],
    currentPhase: 'Uncertain \u2014 leather removed from 2025 eligible commodities. Existing commitments being honored while fund evaluates transition pathway.',
    brandPartnerContext: 'Leather commodity facing strategic review. Kering and Inditex leather sourcing priorities shifting.',
    lastUpdated: '2025-06-01',
  },
  'spain-goat-leather': {
    overview: 'Regenerative goat leather production across multiple Spanish regions through Fundaci\u00f3n Global Nature. Connecting traditional Mediterranean pastoralism with modern supply chain requirements.',
    objectives: [
      'Demonstrate regenerative goat management across 17,000 hectares',
      'Build traceable goat leather supply chain from Spain to European brands',
      'Document biodiversity benefits of extensive goat grazing on Mediterranean landscapes',
      'Create economic incentive model for traditional pastoral communities',
    ],
    challenges: [
      'Leather dropped from 2025 eligible commodities \u2014 project continuation TBD',
      'Small scale relative to other fund projects',
      'Mediterranean pastoralism is declining \u2014 aging producer demographics',
      'Goat leather is a niche market with limited premium differentiation',
    ],
    keyResults: [
      'Regenerative grazing protocols piloted across three regions',
      'Baseline biodiversity assessments completed',
    ],
    currentPhase: 'Uncertain \u2014 leather removed from 2025 eligible commodities.',
    brandPartnerContext: null,
    lastUpdated: '2025-06-01',
  },
  'argentina-patagonia-wool': {
    overview: 'Wildlife Friendly-certified merino wool and mohair production across 300,000 hectares of Patagonian steppe. The project demonstrates that predator coexistence and premium fiber production can reinforce each other.',
    objectives: [
      'Maintain Wildlife Friendly certification across participating ranches',
      'Document recovery of threatened species including Andean cat and guanaco',
      'Achieve sustained 15%+ price premium for certified fiber',
      'Build replicable predator coexistence model for Southern Cone rangelands',
    ],
    challenges: [
      'Remote terrain makes monitoring visits expensive and seasonal',
      'Predator-livestock conflict remains the primary producer concern',
      'Wool market pricing is cyclical \u2014 premium must persist through downturns',
      'Climate change is shifting precipitation patterns across Patagonian steppe',
    ],
    keyResults: [
      'Wildlife Friendly-certified fiber commanding 15% price premium consistently',
      'Documented recovery of threatened Andean cat and guanaco populations',
      'Model adopted by neighboring ranches outside formal project boundary',
    ],
    currentPhase: 'Year 4. Mature implementation \u2014 focus shifting from enrollment to long-term ecological monitoring and market access stabilization.',
    brandPartnerContext: 'Premium merino wool routed to Kering luxury brands. Mohair to specialty textile markets.',
    lastUpdated: '2025-12-01',
  },
  'france-wool': {
    overview: 'Regional wool and sheep leather production in the Midi-Pyr\u00e9n\u00e9es and Occitanie regions of southern France. Epiterre leads implementation focused on connecting regenerative grazing with local textile processing.',
    objectives: [
      'Establish regenerative wool production across 8,000 hectares',
      'Develop regional fiber processing infrastructure',
      'Document soil health improvements from managed grazing',
      'Create a French regenerative wool label with producer premiums',
    ],
    challenges: [
      'Small scale \u2014 8,000 hectares is modest for landscape-level claims',
      'French wool market is small and undervalued compared to Australian/NZ wool',
      'Processing infrastructure gaps \u2014 most French wool exported for processing',
      'Limited baseline monitoring data available',
    ],
    keyResults: [
      'Regenerative grazing network established across Occitanie',
      'Initial soil baseline sampling underway',
    ],
    currentPhase: 'Year 4. Building producer network and establishing monitoring protocols.',
    brandPartnerContext: 'European-origin wool valued by Kering for proximity and traceability.',
    lastUpdated: '2025-09-01',
  },
  'south-africa-wool': {
    overview: 'Working with 280 communal herders in the Eastern Cape on sheep wool production. Conservation South Africa leads implementation, partnering with BKB (dominant regional wool broker marketing 62% of SA wool clip).',
    objectives: [
      'Improve communal rangeland management across 11,000 hectares',
      'Increase herder income through improved wool quality and market access',
      'Establish SOC and rangeland condition baselines',
      'Build replicable model for communal land wool production',
    ],
    challenges: [
      'Communal land tenure creates collective action challenges',
      'Eastern Cape is drought-prone with increasing climate volatility',
      'Herder cooperatives need capacity building for quality standards',
      'BKB market concentration creates negotiation asymmetry for small producers',
    ],
    keyResults: [
      '280 herders enrolled in improved management program',
      'BKB partnership established for market access',
      'Baseline rangeland condition assessments underway',
    ],
    currentPhase: 'Year 4. Deepening herder training and establishing wool quality grading at shearing sheds.',
    brandPartnerContext: 'South African merino is a key sourcing origin for mid-range knitwear.',
    lastUpdated: '2025-09-01',
  },
  'uganda-cotton': {
    overview: '2,000+ cotton farmers on 6,000 hectares of production with 32,000 hectares of associated restoration in the Kidepo landscape. African Wildlife Foundation and DADO lead implementation.',
    objectives: [
      'Improve cotton yields through regenerative practices',
      'Reduce human-wildlife conflict in Kidepo landscape',
      'Restore 32,000 hectares of degraded land adjacent to cotton production',
      'Connect cotton income to conservation incentives',
    ],
    challenges: [
      'Post-conflict region with infrastructure limitations',
      'Human-wildlife conflict is acute \u2014 elephants and crops',
      'Limited monitoring data available to date',
    ],
    keyResults: [
      'Improved cotton yields documented',
      'Reduced human-wildlife conflict incidents reported',
    ],
    currentPhase: 'Year 2. Scaling enrollment while establishing monitoring systems.',
    brandPartnerContext: null,
    lastUpdated: '2024-12-01',
  },
  'india-cotton-wfen': {
    overview: '900 women cotton farmers in the Pench-Satpura-Melghat tiger corridor of central India. WFEN and WWF-India are integrating wildlife conservation with cotton production in a critical biodiversity hotspot.',
    objectives: [
      'Support 900 women farmers in adopting wildlife-friendly cotton practices',
      'Reduce pesticide use in tiger corridor buffer zones',
      'Document biodiversity co-benefits of regenerative cotton',
      'Build farmer cooperatives for market access',
    ],
    challenges: [
      'Tiger corridor regulations constrain some agricultural practices',
      'Small project scale limits landscape-level impact claims',
      'Data collection in remote forest-fringe communities is challenging',
    ],
    keyResults: [
      '900 women farmers enrolled in wildlife-friendly cotton program',
      'Pesticide reduction documented in buffer zone farms',
    ],
    currentPhase: 'Year 2. Building cooperative structures and establishing biodiversity monitoring protocols.',
    brandPartnerContext: null,
    lastUpdated: '2024-12-01',
  },
  'pakistan-cotton': {
    overview: 'Cotton regeneration project across 15,000 hectares in Punjab and Sindh provinces. Implementation partner to be confirmed. Project design phase underway.',
    objectives: [
      'Establish regenerative cotton production in Pakistani cotton belt',
      'Reduce water consumption through improved irrigation practices',
      'Build soil health monitoring capacity',
      'Connect producers to sustainable cotton supply chains',
    ],
    challenges: [
      'Water scarcity is the dominant constraint in Punjab/Sindh cotton regions',
      'Implementation partner selection still in progress',
      'Limited baseline data available',
    ],
    keyResults: [],
    currentPhase: 'Early implementation. Partner selection and project design underway.',
    brandPartnerContext: null,
    lastUpdated: '2024-12-01',
  },
  'turkey-cotton': {
    overview: 'New 2025 geography. Project details pending grantee selection and project design.',
    objectives: ['To be defined during project inception phase'],
    challenges: ['To be assessed during project design'],
    keyResults: [],
    currentPhase: 'Pre-inception. Geography approved in 2025 funding cycle.',
    brandPartnerContext: null,
    lastUpdated: '2025-01-01',
  },
  'australia-wool': {
    overview: 'New 2025 geography. Project details pending grantee selection and project design.',
    objectives: ['To be defined during project inception phase'],
    challenges: ['To be assessed during project design'],
    keyResults: [],
    currentPhase: 'Pre-inception. Geography approved in 2025 funding cycle.',
    brandPartnerContext: null,
    lastUpdated: '2025-01-01',
  },
  'nz-wool': {
    overview: 'New 2025 geography. Project details pending grantee selection and project design.',
    objectives: ['To be defined during project inception phase'],
    challenges: ['To be assessed during project design'],
    keyResults: [],
    currentPhase: 'Pre-inception. Geography approved in 2025 funding cycle.',
    brandPartnerContext: null,
    lastUpdated: '2025-01-01',
  },
};

// ── Biodiversity Seed Data ──────────────────────────────────────────────────

export const projectBiodiversity: Record<string, ProjectBiodiversity> = {
  'mongolia-cashmere': {
    ecoregion: 'Mongolian-Manchurian Grassland',
    biome: 'Temperate Grasslands, Savannas & Shrublands',
    nearestProtectedArea: 'Khustain Nuruu National Park',
    distanceToProtectedAreaKm: 85,
    keySpecies: ['Przewalski\'s horse', 'Mongolian gazelle', 'Snow leopard', 'Corsac fox'],
    threatenedSpecies: ['Snow leopard (Vulnerable)', 'Mongolian saiga (Endangered)'],
    biodiversityNotes: 'Central Mongolian grasslands support critical migratory corridors. Overgrazing from cashmere goats is a primary degradation driver.',
  },
  'india-cotton-oca': {
    ecoregion: 'Deccan Thorn Scrub Forests',
    biome: 'Tropical & Subtropical Dry Broadleaf Forests',
    nearestProtectedArea: 'Melghat Tiger Reserve',
    distanceToProtectedAreaKm: 120,
    keySpecies: ['Indian peafowl', 'Nilgai', 'Indian jackal', 'Sloth bear'],
    threatenedSpecies: ['Indian vulture (Critically Endangered)', 'Great Indian bustard (Critically Endangered)'],
    biodiversityNotes: 'Cotton belt of central India intersects with critical wildlife corridors. Organic farming reduces pesticide poisoning of non-target species.',
  },
  'argentina-leather': {
    ecoregion: 'Dry Chaco',
    biome: 'Tropical & Subtropical Dry Broadleaf Forests',
    nearestProtectedArea: 'Copo National Park',
    distanceToProtectedAreaKm: 60,
    keySpecies: ['Giant armadillo', 'Chacoan peccary', 'Jaguar', 'Crowned eagle'],
    threatenedSpecies: ['Chacoan peccary (Endangered)', 'Giant armadillo (Vulnerable)', 'Jaguar (Near Threatened)'],
    biodiversityNotes: 'Gran Chaco is the second-largest forest in South America and one of the highest deforestation frontiers globally. Sustainable ranching is critical to halting habitat loss.',
  },
  'spain-goat-leather': {
    ecoregion: 'Iberian Sclerophyllous and Semi-deciduous Forests',
    biome: 'Mediterranean Forests, Woodlands & Scrub',
    nearestProtectedArea: 'Caba\u00f1eros National Park',
    distanceToProtectedAreaKm: 50,
    keySpecies: ['Iberian lynx', 'Spanish imperial eagle', 'Red deer', 'Wild boar'],
    threatenedSpecies: ['Iberian lynx (Endangered)', 'Spanish imperial eagle (Vulnerable)'],
    biodiversityNotes: 'Extensive goat grazing maintains open Mediterranean landscapes that support fire-adapted species and reduce wildfire risk.',
  },
  'argentina-patagonia-wool': {
    ecoregion: 'Patagonian Steppe',
    biome: 'Temperate Grasslands, Savannas & Shrublands',
    nearestProtectedArea: 'Los Alerces National Park',
    distanceToProtectedAreaKm: 40,
    keySpecies: ['Guanaco', 'Andean condor', 'Darwin\'s rhea', 'Andean cat'],
    threatenedSpecies: ['Andean cat (Endangered)', 'Patagonian huemul (Endangered)'],
    biodiversityNotes: 'Wildlife Friendly-certified production has documented recovery of guanaco populations and reduced predator conflict.',
  },
  'france-wool': {
    ecoregion: 'Pyrenees Conifer and Mixed Forests',
    biome: 'Temperate Broadleaf & Mixed Forests',
    nearestProtectedArea: 'Pyrenees National Park',
    distanceToProtectedAreaKm: 30,
    keySpecies: ['Pyrenean chamois', 'Griffon vulture', 'Brown bear', 'Lammergeier'],
    threatenedSpecies: ['Brown bear (reintroduced, Vulnerable regionally)'],
    biodiversityNotes: 'Southern French pastoral landscapes provide habitat connectivity between Pyrenees montane areas and lowland agricultural zones.',
  },
  'south-africa-wool': {
    ecoregion: 'Albany Thickets',
    biome: 'Deserts & Xeric Shrublands',
    nearestProtectedArea: 'Addo Elephant National Park',
    distanceToProtectedAreaKm: 55,
    keySpecies: ['African buffalo', 'Kudu', 'Black-backed jackal', 'Secretary bird'],
    threatenedSpecies: ['Cape vulture (Vulnerable)', 'Riverine rabbit (Critically Endangered)'],
    biodiversityNotes: 'Eastern Cape communal rangelands border thicket biome \u2014 one of the most threatened vegetation types in South Africa.',
  },
  'uganda-cotton': {
    ecoregion: 'East Sudanian Savanna',
    biome: 'Tropical & Subtropical Grasslands, Savannas & Shrublands',
    nearestProtectedArea: 'Kidepo Valley National Park',
    distanceToProtectedAreaKm: 15,
    keySpecies: ['African elephant', 'Lion', 'Rothschild\'s giraffe', 'African wild dog'],
    threatenedSpecies: ['African wild dog (Endangered)', 'Rothschild\'s giraffe (Vulnerable)'],
    biodiversityNotes: 'Adjacent to Kidepo Valley NP \u2014 human-wildlife conflict (especially elephants) is the primary conservation challenge in the landscape.',
  },
  'india-cotton-wfen': {
    ecoregion: 'Central Deccan Plateau Dry Deciduous Forests',
    biome: 'Tropical & Subtropical Dry Broadleaf Forests',
    nearestProtectedArea: 'Pench Tiger Reserve',
    distanceToProtectedAreaKm: 5,
    keySpecies: ['Bengal tiger', 'Indian leopard', 'Dhole', 'Gaur'],
    threatenedSpecies: ['Bengal tiger (Endangered)', 'Dhole (Endangered)'],
    biodiversityNotes: 'Project is in the Pench-Satpura-Melghat tiger corridor \u2014 one of central India\'s most critical wildlife connectivity zones.',
  },
  'pakistan-cotton': {
    ecoregion: 'Indus Valley Desert',
    biome: 'Deserts & Xeric Shrublands',
    nearestProtectedArea: 'Lal Suhanra National Park',
    distanceToProtectedAreaKm: 100,
    keySpecies: ['Awaiting CI input'],
    threatenedSpecies: ['Awaiting CI input'],
    biodiversityNotes: 'Punjab/Sindh cotton belt is heavily irrigated agricultural land. Biodiversity context to be assessed during project design.',
  },
  'turkey-cotton': {
    ecoregion: 'Eastern Mediterranean Conifer-Sclerophyllous-Broadleaf Forests',
    biome: 'Mediterranean Forests, Woodlands & Scrub',
    nearestProtectedArea: 'To be determined',
    distanceToProtectedAreaKm: 0,
    keySpecies: ['Awaiting CI input'],
    threatenedSpecies: ['Awaiting CI input'],
    biodiversityNotes: 'Biodiversity assessment pending project inception.',
  },
  'australia-wool': {
    ecoregion: 'Southeast Australia Temperate Forests',
    biome: 'Temperate Broadleaf & Mixed Forests',
    nearestProtectedArea: 'To be determined',
    distanceToProtectedAreaKm: 0,
    keySpecies: ['Awaiting CI input'],
    threatenedSpecies: ['Awaiting CI input'],
    biodiversityNotes: 'Biodiversity assessment pending project inception.',
  },
  'nz-wool': {
    ecoregion: 'Canterbury-Otago Tussock Grasslands',
    biome: 'Temperate Grasslands, Savannas & Shrublands',
    nearestProtectedArea: 'To be determined',
    distanceToProtectedAreaKm: 0,
    keySpecies: ['Awaiting CI input'],
    threatenedSpecies: ['Awaiting CI input'],
    biodiversityNotes: 'Biodiversity assessment pending project inception.',
  },
};

// ── Animal Welfare Seed Data ────────────────────────────────────────────────

export const projectAnimalWelfare: Record<string, ProjectAnimalWelfare> = {
  'mongolia-cashmere': {
    applicable: true,
    livestockType: 'Cashmere goats',
    estimatedHeadcount: 850000,
    stockingDensity: 'Varies \u2014 rangeland carrying capacity under assessment',
    certifications: ['SFA (Sustainable Fibre Alliance)'],
    welfareNotes: 'SFA has certified 21,585+ herders across 17 provinces. Key welfare concern is winter dzud mortality events \u2014 satellite-informed herd allocation aims to reduce exposure.',
    practicesDocumented: ['Satellite-informed grazing allocation', 'Winter preparation protocols', 'Veterinary access programs'],
  },
  'india-cotton-oca': {
    applicable: false,
    livestockType: 'N/A',
    estimatedHeadcount: null,
    stockingDensity: null,
    certifications: [],
    welfareNotes: 'Cotton production project. Animal welfare principle not directly applicable. See Biodiversity tab for wildlife context.',
    practicesDocumented: [],
  },
  'argentina-leather': {
    applicable: true,
    livestockType: 'Cattle',
    estimatedHeadcount: 12000,
    stockingDensity: 'Variable across Gran Chaco rangelands',
    certifications: [],
    welfareNotes: 'Cattle ranching in Gran Chaco dry forest. Welfare assessment pending \u2014 focus has been on deforestation-free supply chains.',
    practicesDocumented: ['Deforestation-free ranching protocols'],
  },
  'spain-goat-leather': {
    applicable: true,
    livestockType: 'Goats',
    estimatedHeadcount: 3500,
    stockingDensity: 'Traditional extensive grazing \u2014 low density',
    certifications: [],
    welfareNotes: 'Traditional Mediterranean extensive goat herding. Welfare standards aligned with EU animal welfare regulations.',
    practicesDocumented: ['Extensive grazing management', 'Traditional husbandry practices'],
  },
  'argentina-patagonia-wool': {
    applicable: true,
    livestockType: 'Merino sheep and Angora goats',
    estimatedHeadcount: 45000,
    stockingDensity: 'Low \u2014 Patagonian steppe carrying capacity limits',
    certifications: ['Wildlife Friendly Enterprise Network'],
    welfareNotes: 'Wildlife Friendly certification requires predator coexistence protocols. No mulesing practiced. Low stocking density due to harsh steppe conditions.',
    practicesDocumented: ['Predator coexistence (non-lethal deterrents)', 'Mulesing-free certification', 'Rotational grazing'],
  },
  'france-wool': {
    applicable: true,
    livestockType: 'Sheep',
    estimatedHeadcount: 8200,
    stockingDensity: 'Moderate \u2014 managed alpine/sub-alpine pastures',
    certifications: [],
    welfareNotes: 'French sheep production under EU animal welfare framework. Regenerative grazing protocols aim to improve pasture quality alongside welfare.',
    practicesDocumented: ['Rotational grazing', 'EU-compliant welfare standards'],
  },
  'south-africa-wool': {
    applicable: true,
    livestockType: 'Sheep (merino and indigenous breeds)',
    estimatedHeadcount: 15000,
    stockingDensity: 'Communal grazing \u2014 stocking rates under assessment',
    certifications: [],
    welfareNotes: 'Communal herding in Eastern Cape. BKB partnership includes wool quality training which indirectly improves animal health (nutrition, shearing practices).',
    practicesDocumented: ['Improved shearing practices', 'Nutrition management training'],
  },
  'uganda-cotton': {
    applicable: false,
    livestockType: 'N/A',
    estimatedHeadcount: null,
    stockingDensity: null,
    certifications: [],
    welfareNotes: 'Cotton production project. Animal welfare principle not directly applicable. See Biodiversity tab for wildlife context.',
    practicesDocumented: [],
  },
  'india-cotton-wfen': {
    applicable: false,
    livestockType: 'N/A',
    estimatedHeadcount: null,
    stockingDensity: null,
    certifications: [],
    welfareNotes: 'Cotton production project in tiger corridor. Animal welfare principle not directly applicable. See Biodiversity tab for wildlife context.',
    practicesDocumented: [],
  },
  'pakistan-cotton': {
    applicable: false,
    livestockType: 'N/A',
    estimatedHeadcount: null,
    stockingDensity: null,
    certifications: [],
    welfareNotes: 'Cotton production project. Animal welfare principle not directly applicable.',
    practicesDocumented: [],
  },
  'turkey-cotton': {
    applicable: false,
    livestockType: 'N/A',
    estimatedHeadcount: null,
    stockingDensity: null,
    certifications: [],
    welfareNotes: 'Cotton production project. Animal welfare principle not directly applicable.',
    practicesDocumented: [],
  },
  'australia-wool': {
    applicable: true,
    livestockType: 'Sheep (merino)',
    estimatedHeadcount: 22000,
    stockingDensity: 'Low-moderate \u2014 semi-arid pastoral zones',
    certifications: ['RWS (Responsible Wool Standard) \u2014 pending'],
    welfareNotes: 'Australian merino wool production. Mulesing status under review with transition to pain-relief protocols. RWS certification in progress.',
    practicesDocumented: ['Pain-relief shearing protocols', 'Predator management (non-lethal preferred)'],
  },
  'nz-wool': {
    applicable: true,
    livestockType: 'Sheep (crossbred and merino)',
    estimatedHeadcount: 18000,
    stockingDensity: 'Moderate \u2014 temperate pastoral grasslands',
    certifications: ['ZQ Merino', 'NZ Farm Assurance Programme'],
    welfareNotes: 'New Zealand is mulesing-free by industry practice. ZQ certification ensures animal welfare baseline. Focus on winter shelter adequacy and lambing survival rates.',
    practicesDocumented: ['Mulesing-free production', 'Winter shelter programs', 'Lambing survival monitoring'],
  },
};

// ── Livelihood Context Seed Data ────────────────────────────────────────────

export const projectLivelihoodContext: Record<string, ProjectLivelihoodContext> = {
  'mongolia-cashmere': {
    countryCode: 'MNG',
    subnationalRegion: 'Central Mongolia',
    estimatedBeneficiaries: null,
    beneficiaryBreakdown: null,
    averageFarmSize: 'N/A \u2014 nomadic rangeland',
    primaryLivelihood: 'Nomadic cashmere herding',
    indigenousContext: 'Approximately 40% of Mongolia\'s population are nomadic or semi-nomadic herders. Cashmere herding is a traditional livelihood practice.',
    incomeContext: 'Average herder household income below national median. Cashmere represents primary cash income for most herding families.',
    livelihoodNotes: 'Livelihood vulnerability tied to dzud (severe winter) events and cashmere price volatility. SFA certification aims to provide income stability through quality premiums.',
  },
  'india-cotton-oca': {
    countryCode: 'IND',
    subnationalRegion: 'Maharashtra / Madhya Pradesh',
    estimatedBeneficiaries: 50000,
    beneficiaryBreakdown: 'Majority women smallholders',
    averageFarmSize: '< 2 hectares',
    primaryLivelihood: 'Smallholder cotton farming',
    indigenousContext: 'Significant Scheduled Tribe and Scheduled Caste populations in project districts.',
    incomeContext: 'Below state average rural household income. Organic premium represents 10% income uplift.',
    livelihoodNotes: 'Cotton belt of central India has high farmer indebtedness. Organic transition reduces input costs (no purchased pesticides/fertilizers) while premium pricing increases revenue.',
  },
  'argentina-leather': {
    countryCode: 'ARG',
    subnationalRegion: 'Gran Chaco',
    estimatedBeneficiaries: null,
    beneficiaryBreakdown: null,
    averageFarmSize: 'Large ranches \u2014 variable',
    primaryLivelihood: 'Cattle ranching',
    indigenousContext: 'Indigenous Wichi, Toba, and Mocovi communities present in project area.',
    incomeContext: 'Rural poverty rates in Gran Chaco significantly above national average.',
    livelihoodNotes: 'Leather supply chain provides primary income for rural communities. Indigenous producers face market access barriers.',
  },
  'spain-goat-leather': {
    countryCode: 'ESP',
    subnationalRegion: 'Multiple Spanish regions',
    estimatedBeneficiaries: null,
    beneficiaryBreakdown: null,
    averageFarmSize: 'Small to medium pastoral holdings',
    primaryLivelihood: 'Traditional goat herding',
    indigenousContext: null,
    incomeContext: 'Rural depopulation is a major challenge. Traditional pastoralism provides marginal incomes.',
    livelihoodNotes: 'Mediterranean pastoralism faces demographic decline. Young people leaving rural areas for urban employment.',
  },
  'argentina-patagonia-wool': {
    countryCode: 'ARG',
    subnationalRegion: 'Patagonia',
    estimatedBeneficiaries: null,
    beneficiaryBreakdown: null,
    averageFarmSize: 'Large estancias (5,000\u201350,000 ha)',
    primaryLivelihood: 'Sheep and goat ranching',
    indigenousContext: 'Mapuche communities present in some project areas.',
    incomeContext: 'Rancher income dependent on wool price cycles. 15% Wildlife Friendly premium provides stability.',
    livelihoodNotes: 'Patagonian ranching is capital-intensive but low-margin. Premium certification provides meaningful income differentiation.',
  },
  'france-wool': {
    countryCode: 'FRA',
    subnationalRegion: 'Midi-Pyr\u00e9n\u00e9es / Occitanie',
    estimatedBeneficiaries: null,
    beneficiaryBreakdown: null,
    averageFarmSize: 'Small to medium (50\u2013200 ha)',
    primaryLivelihood: 'Sheep farming (wool + meat)',
    indigenousContext: null,
    incomeContext: 'French sheep farmers receive EU Common Agricultural Policy subsidies. Wool is a minor income stream \u2014 meat is primary.',
    livelihoodNotes: 'Wool historically undervalued in France. Project aims to create regional premium brand to make wool a meaningful income stream.',
  },
  'south-africa-wool': {
    countryCode: 'ZAF',
    subnationalRegion: 'Eastern Cape',
    estimatedBeneficiaries: 280,
    beneficiaryBreakdown: 'Communal herders, majority male',
    averageFarmSize: 'Communal grazing \u2014 shared land',
    primaryLivelihood: 'Communal sheep herding',
    indigenousContext: 'Predominantly Xhosa communities on communal land.',
    incomeContext: 'Eastern Cape is one of South Africa\'s poorest provinces. Wool income supplemented by social grants.',
    livelihoodNotes: 'Communal land tenure means individual herders cannot own or lease land. BKB partnership provides market access that individual herders cannot achieve alone.',
  },
  'uganda-cotton': {
    countryCode: 'UGA',
    subnationalRegion: 'Kidepo Landscape (Karamoja/Acholi)',
    estimatedBeneficiaries: 2000,
    beneficiaryBreakdown: null,
    averageFarmSize: '< 2 hectares',
    primaryLivelihood: 'Smallholder cotton farming + subsistence agriculture',
    indigenousContext: 'Karamojong pastoralist communities transitioning to settled agriculture.',
    incomeContext: 'Among the poorest regions in Uganda. Cotton is a critical cash crop.',
    livelihoodNotes: 'Post-conflict region with limited infrastructure. Conservation-agriculture integration aims to provide both ecological and economic benefits.',
  },
  'india-cotton-wfen': {
    countryCode: 'IND',
    subnationalRegion: 'Pench-Satpura-Melghat Corridor',
    estimatedBeneficiaries: 900,
    beneficiaryBreakdown: '900 women farmers',
    averageFarmSize: '< 2 hectares',
    primaryLivelihood: 'Smallholder cotton farming',
    indigenousContext: 'Significant tribal (Adivasi) populations in forest-fringe communities.',
    incomeContext: 'Forest-fringe communities with limited market access. Cotton is primary cash crop.',
    livelihoodNotes: 'Women farmers face additional barriers to market access and financial services. Cooperative building is a key project objective.',
  },
  'pakistan-cotton': {
    countryCode: 'PAK',
    subnationalRegion: 'Punjab / Sindh',
    estimatedBeneficiaries: null,
    beneficiaryBreakdown: null,
    averageFarmSize: 'Small to medium (2\u201310 ha)',
    primaryLivelihood: 'Cotton farming',
    indigenousContext: null,
    incomeContext: 'Awaiting CI input.',
    livelihoodNotes: 'Pakistan is the 4th largest cotton producer globally. Punjab/Sindh cotton belt is heavily irrigated and faces water scarcity challenges.',
  },
  'turkey-cotton': {
    countryCode: 'TUR',
    subnationalRegion: 'Southeastern Anatolia',
    estimatedBeneficiaries: null,
    beneficiaryBreakdown: null,
    averageFarmSize: null,
    primaryLivelihood: 'Cotton farming',
    indigenousContext: null,
    incomeContext: 'Awaiting CI input.',
    livelihoodNotes: 'Subnational livelihood context to be assessed during project inception.',
  },
  'australia-wool': {
    countryCode: 'AUS',
    subnationalRegion: 'New South Wales / Victoria',
    estimatedBeneficiaries: null,
    beneficiaryBreakdown: null,
    averageFarmSize: 'Large pastoral holdings',
    primaryLivelihood: 'Wool farming',
    indigenousContext: null,
    incomeContext: 'Awaiting CI input.',
    livelihoodNotes: 'Subnational livelihood context to be assessed during project inception.',
  },
  'nz-wool': {
    countryCode: 'NZL',
    subnationalRegion: 'Canterbury / Otago',
    estimatedBeneficiaries: null,
    beneficiaryBreakdown: null,
    averageFarmSize: 'Large pastoral holdings',
    primaryLivelihood: 'Sheep farming (wool + meat)',
    indigenousContext: null,
    incomeContext: 'Awaiting CI input.',
    livelihoodNotes: 'Subnational livelihood context to be assessed during project inception.',
  },
};

// ── Fund Summary ────────────────────────────────────────────────────────────

export const fundSummary: FundSummary = {
  totalHectares: 1100000,
  directHectares: 845000,
  indirectHectares: 267000,
  totalProjects: 13,
  totalCountries: 8,
  totalBeneficiaries: 105000,
  launchYear: 2021,
  targetHectares: 1000000,
  commodities: ['cotton', 'wool', 'cashmere', 'leather'],
  activeCommodities2025: ['cotton', 'wool', 'cashmere'],
  brandPartners: ['Kering', 'Inditex'],
  grantRange2024: { min: 120000, max: 620000 },
  grantRange2025: { min: 300000, max: 600000 },
};

// ── Data Completeness (updated with 6 principles) ──────────────────────────

export const dataCompleteness: Record<string, DataCompleteness> = {
  'mongolia-cashmere': {
    climate: 'complete',
    soil: 'partial',
    water: 'partial',
    biodiversity: 'partial',
    livelihoods: 'partial',
    animalWelfare: 'partial',
    score: 50,
    lastUpdated: '2024-09-15',
  },
  'india-cotton-oca': {
    climate: 'complete',
    soil: 'complete',
    water: 'partial',
    biodiversity: 'complete',
    livelihoods: 'complete',
    animalWelfare: 'complete',
    score: 88,
    lastUpdated: '2024-11-20',
  },
  'argentina-leather': {
    climate: 'complete',
    soil: 'partial',
    water: 'partial',
    biodiversity: 'partial',
    livelihoods: 'partial',
    animalWelfare: 'partial',
    score: 42,
    lastUpdated: '2024-06-10',
  },
  'spain-goat-leather': {
    climate: 'complete',
    soil: 'partial',
    water: 'partial',
    biodiversity: 'partial',
    livelihoods: 'partial',
    animalWelfare: 'partial',
    score: 42,
    lastUpdated: '2024-03-22',
  },
  'argentina-patagonia-wool': {
    climate: 'complete',
    soil: 'complete',
    water: 'complete',
    biodiversity: 'complete',
    livelihoods: 'partial',
    animalWelfare: 'complete',
    score: 85,
    lastUpdated: '2024-10-05',
  },
  'france-wool': {
    climate: 'complete',
    soil: 'partial',
    water: 'partial',
    biodiversity: 'partial',
    livelihoods: 'partial',
    animalWelfare: 'partial',
    score: 50,
    lastUpdated: '2024-07-18',
  },
  'south-africa-wool': {
    climate: 'complete',
    soil: 'partial',
    water: 'partial',
    biodiversity: 'partial',
    livelihoods: 'complete',
    animalWelfare: 'partial',
    score: 62,
    lastUpdated: '2024-08-30',
  },
  'uganda-cotton': {
    climate: 'complete',
    soil: 'partial',
    water: 'partial',
    biodiversity: 'partial',
    livelihoods: 'partial',
    animalWelfare: 'complete',
    score: 50,
    lastUpdated: '2024-09-01',
  },
  'india-cotton-wfen': {
    climate: 'complete',
    soil: 'partial',
    water: 'partial',
    biodiversity: 'partial',
    livelihoods: 'partial',
    animalWelfare: 'complete',
    score: 50,
    lastUpdated: '2024-05-14',
  },
  'pakistan-cotton': {
    climate: 'complete',
    soil: 'partial',
    water: 'partial',
    biodiversity: 'partial',
    livelihoods: 'partial',
    animalWelfare: 'complete',
    score: 42,
    lastUpdated: '2024-11-01',
  },
  'turkey-cotton': {
    climate: 'partial',
    soil: 'partial',
    water: 'partial',
    biodiversity: 'partial',
    livelihoods: 'partial',
    animalWelfare: 'complete',
    score: 33,
    lastUpdated: '2024-10-15',
  },
  'australia-wool': {
    climate: 'partial',
    soil: 'partial',
    water: 'partial',
    biodiversity: 'partial',
    livelihoods: 'partial',
    animalWelfare: 'partial',
    score: 25,
    lastUpdated: '2024-12-01',
  },
  'nz-wool': {
    climate: 'partial',
    soil: 'partial',
    water: 'partial',
    biodiversity: 'partial',
    livelihoods: 'partial',
    animalWelfare: 'partial',
    score: 25,
    lastUpdated: '2024-12-01',
  },
};
